### ISSUE TITLE
API includes protobuf references

### ISSUE THREAD

**Issue by eamonnmcmanus** [GoogleCloudPlatform/gcloud-java#100]
Explicitly, or implicitly. For example, [StructuredQuery](http://googlecloudplatform.github.io/gcloud-java/apidocs/com/google/gcloud/datastore/StructuredQuery.html) has protected methods `fromPb`, `populatePb`, and `toPb` which should not appear in the API.

**Comment by aozarov** [comment]
This is unintentional. 

I would expect changing `com.google.gcloud.datastore.Serializable#fromPb` to package scope to fix most (if not all) of the `fromPb` issues.

We should probably change `readResolve` to package scope as well.
