### ISSUE TITLE
Need an easy way to contruct a Key with parent

### ISSUE THREAD

**Issue by seymores** [GoogleCloudPlatform/gcloud-java#1003]
Maybe I missed some docs but I can't figure out how to construct a key with parent. Definitely need an example on how to do this.
I'm using version 0.2.1.

**Comment by ajkannan** [comment]
Hi @seymores, [this Cloud Datastore docs page](https://cloud.google.com/datastore/docs/concepts/entities#ancestor_paths) has some text and a short example on creating a key with a parent.

**Comment by ajkannan** [comment]
In addition to the example in the above link (which uses `PathElement`), `gcloud-java` also has a shorthand for adding a parent (see the methods 2nd and 3rd from the bottom in [`Key`'s API docs page](http://googlecloudplatform.github.io/gcloud-java/0.2.1/apidocs/com/google/cloud/datastore/Key.html#builder(com.google.cloud.datastore.Key,%20java.lang.String,%20java.lang.String)).  For example, if you have a parent `myParentKey` of type `Key`, you can use something like:

```
Key childKey = Key.builder(myParentKey, "ChildKeyKind", "ChildKeyName").build();
```

**Comment by volgin** [comment]
For anyone else looking at this issue:

        Key key = datastore.newKeyFactory()
        		.projectId(PROJECT)
        		.kind(ENTITY_KIND)
        		.ancestors(PathElement.of(PARENT_KIND, PARENT_ID))
        		.newKey(ID_OR_NAME);

**Comment by mziccard** [comment]
Closing this as both @ajkannan and @volgin answered. Thanks guys.
