### ISSUE TITLE
Allow users to set the scheduled executor service

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#1005]
grpc-based services use a `ScheduledExecutorService`. We should allow users to set an executor other than the default one in the service options.

Related to this: should we create an abstract option class for grpc-based services (that extends `ServiceOptions`?) That could expose some of the grpc-only configurations like setting the executor or converting the connection timeouts (see [here](https://github.com/GoogleCloudPlatform/gcloud-java/pull/1001#discussion_r63060327)).

/cc @aozarov @ajkannan

**Comment by ajkannan** [comment]
+1 for creating an abstract options subclass of `ServiceOptions` for gRPC configs

**Comment by aozarov** [comment]
I have the feeling that we may need to have one top-level abstract service options and 2 other abstract sub classes for apiclient and gRPC.  Aside from executor there are other differences such as the way timeout is handled.

**Comment by mziccard** [comment]
This was closed in #1011
