### ISSUE TITLE
StorageImpl.signUrl generates invalid URLs for objects names with leading /

### ISSUE THREAD

**Issue by clementdenis** [GoogleCloudPlatform/gcloud-java#1006]
The generated URL contains zero-chars.

The problem is probably here: https://github.com/GoogleCloudPlatform/gcloud-java/compare/master...clementdenis:patch-1

The method should either reject object names leading slash, or handle them correctly.

**Comment by mziccard** [comment]
Hi @clementdenis, nice catch!

Would you mind sending a PR? Your patch looks good to me.

**Comment by clementdenis** [comment]
Done! See #1008
