### ISSUE TITLE
Storage example should show how to set ACL

### ISSUE THREAD

**Issue by volgin** [GoogleCloudPlatform/gcloud-java#1012]
ACLs are not even mentioned in the examples. Example needs to show both how to set a specific ACL and how to set a PredefinedAcl.

When I use this this code, the console Cloud Storage viewer does not show items as shared publicly:

	storage.create(coverBlob, coverImage,
		BlobTargetOption.predefinedAcl(PredefinedAcl.PUBLIC_READ));

So it's not clear what this code is supposed to do.

Am I right to assume that ACL should be set on BlobInfo like this?

        .acl(Arrays.asList(Acl.of(User.ofAllUsers(), Role.READER)))

If this is correct, is it enough, or should be used together with `BlobTargetOption.predefinedAcl(PredefinedAcl.PUBLIC_READ)`?

**Comment by mziccard** [comment]
ACLs and predefined ACLs are concepts of Cloud Storage with a dedicated [documentation page](https://cloud.google.com/storage/docs/access-control/lists) that should help you understand the different between ACLs and predefined ACLs. We kept the same name so that users familiar with Storage concepts should feel quite at home.

The following code:
```java
storage.create(coverBlob, coverImage,
    BlobTargetOption.predefinedAcl(PredefinedAcl.PUBLIC_READ));
```
Sets the predefined ACL to `PUBLIC_READ`, predefined ACLs are documented by the service [here](https://cloud.google.com/storage/docs/access-control/lists#predefined-acl). The `PUBLIC_READ` predefined ACL corresponds to setting the following permissions:
- Object owner gets `OWNER` access 
- `allUsers` get `READER` access

I just tried the code and the created blob is correctly shown in the web Console as "Shared publicly".

This other code:
```java
.acl(Arrays.asList(Acl.of(User.ofAllUsers(), Role.READER)))
```
Sets the ACL for the blob (a much finer control is possible, when compared to the sole predefined ACLs). In your code you are just setting following permission:
- `allUsers` get `READER` access

Even in this second case the web Console correctly marks the blob as "Shared publicly".

If your goal is to make a blob publicly available both codes will do it.

**Comment by volgin** [comment]
This is how objects look in my bucket when I upload them with the PredefinedAcl:

<img width="1171" alt="screen shot 2016-05-17 at 1 16 51 am" src="https://cloud.githubusercontent.com/assets/297748/15311874/41e68dd8-1bcd-11e6-820b-8cb7cbbc41ab.png">

As you can see, Share Publicly checkbox is missing. Selecting objects and pressing "Share Publicly" button has no effect.

**Comment by mziccard** [comment]
As I said previously I tried this code (and several other combinations):
```java
storage.create(BlobInfo.builder("my-bucket", "test-acl").build(),
    BlobTargetOption.predefinedAcl(PredefinedAcl.PUBLIC_READ));

storage.create(BlobInfo.builder("my-bucket", "test-acl-with-content").build(),
    "Hello, ACL!".getBytes(), BlobTargetOption.predefinedAcl(PredefinedAcl.PUBLIC_READ));
```
And it works just fine:
<img width="993" alt="screen shot 2016-05-17 at 9 01 27 am" src="https://cloud.githubusercontent.com/assets/450933/15313826/25af9178-1c0e-11e6-84c5-91b9d2a3b048.png">

Are you sure you are using the code you shared to create the blobs? If you then get them with cloud-java what does `blob.acl()` contain?

**Comment by volgin** [comment]
1. Yes, I copied the exact code that I use.

2. I tried accessing these images from an unauthenticated browser, and they do show up. So missing checkboxes from the Cloud Storage viewer is the only problem/source of confusion.

Note that if I rename the object, the checkbox appears (unchecked, which is the expected behavior).

**Comment by aozarov** [comment]
Maybe @brandonY has some insights why the Cloud Storage Viewer behaves that way.

**Comment by mziccard** [comment]
This is weird. Now I am experiencing the problem as well, and it seems not to be a problem with just the web console. If I create a blob:
```java
storage.create(BlobInfo.builder("my-bucket", "test-acl").build(),
        BlobTargetOption.predefinedAcl(PredefinedAcl.PUBLIC_READ));
```
The HTTP response (to the uploading POST request) correctly has the expected ACLs:
```json
{
 "kind": "storage#object",
 "id": "my-bucket/test-acl/1463505795940000",
 "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket/o/test-acl",
 "name": "test-acl",
 "bucket": "my-bucket",
 "generation": "1463505795940000",
 "metageneration": "1",
 "contentType": "text/plain",
 "timeCreated": "2016-05-17T17:23:15.931Z",
 "updated": "2016-05-17T17:23:15.931Z",
 "storageClass": "STANDARD",
 "size": "0",
 "md5Hash": "1B2M2Y8AsgTpgAmY7PhCfg==",
 "mediaLink": "https://www.googleapis.com/download/storage/v1/b/my-bucket/o/test-acl?generation=1463505795940000&alt=media",
 "acl": [
  {
   "kind": "storage#objectAccessControl",
   "id": "some-id",
   "selfLink": "some-link",
   "bucket": "my-bucket",
   "object": "test-acl",
   "generation": "1463505795940000",
   "entity": "some-entity",
   "role": "OWNER",
   "entityId": "some-entity-id",
   "etag": "some-tag"
  },
  {
   "kind": "storage#objectAccessControl",
   "id": "my-bucket/test-acl/1463505795940000/allUsers",
   "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket/o/test-acl/acl/allUsers",
   "bucket": "my-bucket",
   "object": "test-acl",
   "generation": "1463505795940000",
   "entity": "allUsers",
   "role": "READER",
   "etag": "CKD93/jP4cwCEAE="
  }
 ],
 "owner": {
  "entity": "my-entity",
  "entityId": "my-entity-id"
 },
 "crc32c": "AAAAAA==",
 "etag": "CKD93/jP4cwCEAE="
}
```
However if I GET the object the ACLs disappeared:

```json
{
 "kind": "storage#object",
 "id": "empty-test-bucket/test-acl/1463505795940000",
 "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket/o/test-acl",
 "name": "test-acl",
 "bucket": "my-bucket",
 "generation": "1463505795940000",
 "metageneration": "1",
 "contentType": "text/plain",
 "timeCreated": "2016-05-17T17:23:15.931Z",
 "updated": "2016-05-17T17:23:15.931Z",
 "storageClass": "STANDARD",
 "size": "0",
 "md5Hash": "1B2M2Y8AsgTpgAmY7PhCfg==",
 "mediaLink": "https://www.googleapis.com/download/storage/v1/b/my-bucket/o/test-acl?generation=1463505795940000&alt=media",
 "crc32c": "AAAAAA==",
 "etag": "CKD93/jP4cwCEAE="
}
```
/cc @Capstan

**Comment by Capstan** [comment]
You need the full projection to get ACLs on normal gets. If you provide an ACL on create or update, you'll get an acl in the response, but otherwise you need to specify full there as well.

**Comment by mziccard** [comment]
@Capstan I am using full projection to get the blob.

What I believe is happening is that the blobs are being created with a service account while the console is being accessed with a different account and thus has no access to the ACL information (@volgin can you confirm you are running this scenario?)

For the console to show the "Shared publicly" mark I used: 
```java
storage.create(BlobInfo.builder("my-bucket", "test-acl")
    .acl(Arrays.asList(Acl.of(User.ofAllUsers(), Acl.Role.READER),
        Acl.of(new User("my@email.com"), Acl.Role.OWNER))).build());
```
Where `"my@email.com"` is the account I use to log to the web console.

@volgin regardless of the fact that you are not seeing the "Shared publicly" mark in the web console I believe they are being properly set.

**Comment by volgin** [comment]
@mziccard - You are correct.

It looks like a bug in web console: I can do anything I want with these objects (rename and delete), which indicates Owner access level, but I do not see the checkbox for "Share publicly".
