### ISSUE TITLE
dns-alpha-batch branch should be deleted

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#1025]
Also, looks like it is ahead few commits which should probably be merged to master before branch delete.

**Comment by mziccard** [comment]
It can be safely deleted. In #940 I took the commits and rebased them on top of master to avoid ugly merges, this is way it says it's 8 commits ahead, but actually it's not.

**Comment by mziccard** [comment]
Branch was deleted
