### ISSUE TITLE
Storage BlobInfo createdTime not present in library

### ISSUE THREAD

**Issue by txomon** [GoogleCloudPlatform/gcloud-java#1032]
Hello,

I have been using the library and checking the [JSON API exposes] [1], as a reference to use Google Cloud Storage, I haven't been able to find these fields:

  * timeCreated
  * any of the encryption attributes

However one can find them in the library this library is relying on: https://developers.google.com/resources/api-libraries/documentation/storage/v1/java/latest/com/google/api/services/storage/model/StorageObject.html

Would it be possible to at least expose the timeCreated field?

Thank you!

[1]: https://cloud.google.com/storage/docs/json_api/v1/objects#resource-representations

**Comment by mziccard** [comment]
Hi @txomon,

thanks for the report. Sure thing, I'll add support for `timeCreated` ASAP. 

We also plan to support customer-supplied encryption keys but that might take I bit longer. I'll keep you posted.

**Comment by mziccard** [comment]
@txomon `createTime` was added in  #1034, it will be available in the next release of `gcloud-java` (that should be out by the end of this week). I added #1037 to track the encryption key issue.
