### ISSUE TITLE
Add support for BigQuery BYTES data type

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#1039]
BigQuery [BYTES](https://cloud.google.com/bigquery/data-types) data type was recently added (see [release notes](https://cloud.google.com/bigquery/release-notes#march_23_2016)). We should add support for it to both [`Field`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-bigquery/src/main/java/com/google/cloud/bigquery/Field.java) and [`FieldValue`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-bigquery/src/main/java/com/google/cloud/bigquery/FieldValue.java) classes.

**Comment by criccomini** [comment]
Any idea when this will be released?

**Comment by mziccard** [comment]
@criccomini Just now :) I just released `gcloud-java 0.2.3` that fixes this issue.

**Comment by criccomini** [comment]
💯
