### ISSUE TITLE
Storage: Emulate directly listing with delim and prefix

### ISSUE THREAD

**Issue by fonzy2013** [GoogleCloudPlatform/gcloud-java#1049]
Anyone knows if it is possible to use prefix and delimiter options at the same time like the following raw REST URL
```
https://www.googleapis.com/storage/v1/b/clientbuilds/o?delimiter=%2F&prefix=dir1%2Fdir2%2F&key={YOUR_API_KEY}
```
(above is from https://developers.google.com/apis-explorer/#p/storage/v1/storage.objects.list?)
Results from this is:
```
{
 "kind": "storage#objects",
 "prefixes": [
  "dir1/dir2/6893940/",
  "dir1/dir2/6893942/"
 ]
}
```

Setting the `prefix` I know how to do with `Storage.BlobListOption.prefix("dir1/dir2/")`but I looked in the code and can't really understand how to set the `delimiter`

**Comment by mziccard** [comment]
You can use the `Storage. BlobListOption.currentDirectory()` option.

Quoting from the javadoc:
> If specified, results are returned in a directory-like mode. Blobs whose names, after a possible `prefix(String)`, do not contain the '/' delimiter are returned as is. Blobs whose names, after a possible `prefix(String)`, contain the '/' delimiter, will have their name truncated after the delimiter and will be returned as Blob objects where only `BlobInfo.blobId()`, `BlobInfo.size()` and `BlobInfo.isDirectory()` are set. For such directory blobs, `BlobId.generation()` returns null, `BlobInfo.size()` returns 0 while `BlobInfo.isDirectory()` returns `true`. Duplicate directory blobs are omitted.

**Comment by fonzy2013** [comment]
So currentDirectory translates to delimiter= in the actual request?
If so it is what I want, however I wouldn't  mind this option exposed the same way the other parameters are exposed. 
Any reasoning why this parameter isn't exposed as BlobListOption.delimiter(String)?

**Comment by mziccard** [comment]
> So currentDirectory translates to delimiter= in the actual request?

Yes, `currentDirectory` translates to `delimiter=/`.

This was thoroughly discussed with service owners [here](https://github.com/GoogleCloudPlatform/gcloud-java/issues/692). Based on service usage, custom delimiters (i.e. delimiters other that `/`) are not used. Also, as far as I know, there are plans to deprecate the use of delimiters other than `/`. Please @Capstan correct me if I am wrong.

**Comment by fonzy2013** [comment]
@mziccard thanks for the answer. Google should update the documentation which isn't very clear:
`delimiter: (String) - Returns results in a directory-like mode. items will contain only objects whose names, aside from the prefix, do not contain delimiter. Objects whose names, aside from the prefix, contain delimiter will have their name, truncated after the delimiter, returned in prefixes. Duplicate prefixes are omitted. (string)`
