### ISSUE TITLE
ExceptionHandler.Interceptor.RetryResult should have a third value, used instead of null

### ISSUE THREAD

**Issue by eamonnmcmanus** [GoogleCloudPlatform/gcloud-java#105]
The methods of [ExceptionHandler.Interceptor](http://googlecloudplatform.github.io/gcloud-java/apidocs/com/google/gcloud/ExceptionHandler.Interceptor.html) return a value that is one of `RetryResult.RETRY`, `RetryResult.ABORT`, or `null`. Instead of `null`, there should be a third `RetryResult` constant. Returning null from the `beforeEval` or `afterEval` methods would then provoke a `NullPointerException`.

**Comment by aozarov** [comment]
Fixed in #181
