### ISSUE TITLE
Startup Script for Instance

### ISSUE THREAD

**Issue by ukman** [GoogleCloudPlatform/gcloud-java#1081]
Hello,
I'm trying to create an instance with startup script. I saw [ComputeExample.java](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-examples/src/main/java/com/google/cloud/examples/compute/ComputeExample.java) but it describes process how to specify metadata for created instance.
How can I correctly specify startup script when create it?

**Comment by mziccard** [comment]
Hi @ukman,

I suggest you have a look at our javadoc that can be found [here](http://googlecloudplatform.github.io/gcloud-java/apidocs/index.html).

When creating an instance you can set the metadata (and hence the startup script) using the [`metadata(Metadata)`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/gcs-nio/gcloud-java-compute/src/main/java/com/google/cloud/compute/InstanceInfo.java#L195) setter of `InstanceInfo.Builder`.

You might want to consider posting this kind of help requests to StackOverflow, using the `gcloud-java` tag.

**Comment by ukman** [comment]
Thanks
