### ISSUE TITLE
Add OAuth Callback URL

### ISSUE THREAD

**Issue by ukman** [GoogleCloudPlatform/gcloud-java#1082]
Hello
I develop app that creates instances with our web app for our clients. Our web app supports Google Cloud OAuth authentification. So for every instances we create DNS name (instance-1.ourcompany.com, instance-2.ourcompany.com...) So next step is to specify OAuth callback urls (http://instance-1.ourcompany.com/oauth/callback ,  http://instance-2.ourcompany.com/oauth/callback ... )
How can I do that via Java API?

**Comment by mziccard** [comment]
It is unclear to me what you are trying to achieve and how this relates to `gcloud-java`. Can you provide more details?

**Comment by ukman** [comment]
Please open [Credential Page](https://console.developers.google.com/apis/credentials?project=_)
Select a project, There is a section Callback URI.
These URIs are used by google to redirect user back to an app. So I need to add/edit/remove these URI from Java via Google Cloud Java API.

Does it make sense?

**Comment by ukman** [comment]
Marco, please take a look at my previous post. Does it make sense?

**Comment by mziccard** [comment]
> Marco, please take a look at my previous post. Does it make sense?

Please don't ping.

I see what you want to do. However this is not supported by gcloud-java and I doubt we will support it any time soon. /cc @jgeewax

**Comment by jgeewax** [comment]
Yea I don't think we have an API yet for managing things in the credentials tab. If we do create an API for that, we'll have to look at adding that feature to gcloud-java.

Sorry about that !

**Comment by ukman** [comment]
Thanks for you help, guys!
