### ISSUE TITLE
README.md - examples don't work w/ the latest (0.0.5) gcloud-java-datastore

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/gcloud-java#112]
There are no:
 - com.google.gcloud.datastore.Datastore
 - com.google.gcloud.datastore.DatastoreFactory

**Comment by waprin** [comment]
It works with the latest 0.0.5, just doesn't look like the artifact has been published to Nexus. You can clone the repo and install locally and it will work.

**Comment by saturnism** [comment]
yeah I know that ;) but that isn't a good user experience...

**Comment by waprin** [comment]
Ah ok, was noting just in case, issue title would be more accurately named latest 0.0.5 isn't released to Nexus. Not sure if Maven is being used right, IMO there should be only one SHA associated with 0.0.5 so this can't be an issue, commits that are not ready for release should be on a SNAPSHOT version number.

**Comment by aozarov** [comment]
Sorry, I neglected to do a maven push after some refactoring. I pushed 0.0.6 to reflect the changes.

**Comment by aozarov** [comment]
gcloud-0.0.6 was pushed and both site and README.md were modified (and no longer suggest LATEST). Travis builds will create a new SNAPSHOT maven artifact. 

Is there anything else associated with this issue that was not covered?

**Comment by aozarov** [comment]
seems like all items in this issue were covered.
