### ISSUE TITLE
Shared access authentication for google cloud storage?

### ISSUE THREAD

**Issue by raintears** [GoogleCloudPlatform/gcloud-java#1132]
Hi,

Is there a way to do shared access using gcloud? I'm coming from azure and s3 and we used to use access key and secret key to construct a token or sas signature for shared access. I can't seem to find any guides on this topic. I see from most tutorials, I need to reference a json file which stores my private key credentials, is it possible to use access key and secret key concept to connect to google cloud storage?

Can anyone please help?

**Comment by mziccard** [comment]
Hi @raintears,

If I understood correctly you might be interested in signed URLs (see official documentation [here](https://cloud.google.com/storage/docs/access-control/signed-urls)). When using `gcloud-java` you can create a signed URL by using [`Storage.signUrl`](http://googlecloudplatform.github.io/gcloud-java/0.2.6/apidocs/com/google/cloud/storage/Storage.html#signUrl(com.google.cloud.storage.BlobInfo,%20long,%20java.util.concurrent.TimeUnit,%20com.google.cloud.storage.Storage.SignUrlOption...)).

**Comment by mziccard** [comment]
This remained open for a while with no follow up. Feel free to reopen this if you have further questions!
