### ISSUE TITLE
Check if Bucket.exists()?

### ISSUE THREAD

**Issue by raintears** [GoogleCloudPlatform/gcloud-java#1133]
Hi,

I still can't understand how can I use bucket.exists from the documentation. I don't even know how to instantiate a new bucket. This is what I did.

Bucket bucket = new Bucket("bucketname");
return bucket.exists();

Apparently I can't instantiate a new bucket like this, so how then can I use bucket.exists()?

**Comment by mziccard** [comment]
Hi @raintears,

`Bucket` is a class that contains all information of a bucket, in contrast with `BucketInfo`, the `Bucket` class also exposes methods to `update` and `delete` the bucket. `Bucket` objects cannot be created directly but are returned by `Storage` methods like [`create`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-storage/src/main/java/com/google/cloud/storage/Storage.java#L1219) and [`get`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-storage/src/main/java/com/google/cloud/storage/Storage.java#L1257).

To check for the existence of a bucket if you do not have an instance of `Bucket` you can do the following:
```java
return storage.get("bucketname", Storage.BucketGetOption.fields()) != null;
```
`storage.get` will return a `Bucket` object or `null` if not found. `Storage.BucketGetOption.fields()` tells the service to return only the bucket name (we don't need to transfer all bucket's fields to check for existence).

**Comment by raintears** [comment]
Thanks @mziccard 

This explanation is more straightforward!

**Comment by kaus22** [comment]
@mziccard which package did you get your Storage class from?
I'm using com.google.api.services.storage.Storage and BucketGetOptions.fields() is not getting resolved.
