### ISSUE TITLE
The httpTransportFactory is not used

### ISSUE THREAD

**Issue by successhawk** [GoogleCloudPlatform/gcloud-java#1138]
If you set the DatastoreOptions' builder's httpTransportFactory it is not used.  The "create" method of the factory is never called.  This does not allow me to configure a proxy.  This is a defect, but is there a workaround to configure a proxy?

`	public static Datastore createService() {
		HttpTransportFactory httpTransportFactory = new HttpTransportWithProxyFactory();
		return DatastoreOptions.builder()
				.httpTransportFactory(httpTransportFactory).build().
			service();
	}
	
	public static class HttpTransportWithProxyFactory implements HttpTransportFactory {
		
		public HttpTransport create() {
			// PUT BREAKPOINT ON NEXT LINE AND IT IS NEVER CALLED
			Proxy proxy = new Proxy(Type.HTTP, new InetSocketAddress("myproxy.com", 8080));
			HttpTransport t = new NetHttpTransport.Builder().setProxy(proxy).build();
			return t;
		}
	}`

**Comment by mziccard** [comment]
Hi @successhawk, thanks for the report. I believe you are right, I'll try to fix this soon. I'll CC you to the pull request so you can give it a try.

**Comment by mziccard** [comment]
@successhawk `gcloud-java 0.2.7` is now out and fixes this issue.

**Comment by successhawk** [comment]
@mziccard Can you check out this related issue? #1210
