### ISSUE TITLE
Is there support for performing random/partial write to a particular offset of a file?

### ISSUE THREAD

**Issue by raintears** [GoogleCloudPlatform/gcloud-java#1145]
I couldn't find documentation that supports this. 

Basically, I have a file uploaded to google cloud and would like to write at a particular offset of the file and save it in gcloud. Is that possible? Something like microsoft azure page blob random write.

Please help thanks!

**Comment by mziccard** [comment]
`gcloud-java` does not have support for random writes. @Capstan does GCS have/plan to add support for random writes?

**Comment by Capstan** [comment]
Not in the near future, no.
