### ISSUE TITLE
Update gcloud-java/datastore to use the v1 API

### ISSUE THREAD

**Issue by eddavisson** [GoogleCloudPlatform/gcloud-java#1165]
The v1 API is now available.

The protos are identical (just a different package name). The only behavioral change is captured in the release notes:
https://cloud.google.com/datastore/release-notes

**Comment by mziccard** [comment]
Hi @eddavisson, thanks for the updated.

I started working on the update but I cannot get the datastore emulator to work with the new release. Is there an emulator that works with the `v1` API? I tried what I believe to be the latest datastore emulator ([cloud-datastore-emulator-1.1.1.zip](https://storage.googleapis.com/gcd/tools/cloud-datastore-emulator-1.1.1.zip)) but it's returning 404 for requests to the `v1` endpoints (as `/v1/projects/<myproject>:<operation>`), while it works for `v1beta3` endpoints (as `/v1beta3/projects/<myproject>:<operation>`). /cc @pcostell 

Also I believe that we must remove the `/datastore` part from the localhost endpoint (see [`DatastoreFactory.buildProjectEndpoint`](https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/master/java/datastore/src/main/java/com/google/datastore/v1/client/DatastoreFactory.java#L101)) as new emulators seem to no longer use it.

**Comment by eddavisson** [comment]
I've uploaded [cloud-datastore-emulator-1.2.0.zip](https://storage.googleapis.com/gcd/tools/cloud-datastore-emulator-1.2.0.zip). Can you see if that works?

You're also correct that you'll need to drop `/datastore` from the localhost endpoint. We're making a similar update to our low-level library.

**Comment by mziccard** [comment]
> I've uploaded cloud-datastore-emulator-1.2.0.zip. Can you see if that works?

I'll try it immediately.

> You're also correct that you'll need to drop /datastore from the localhost endpoint. We're making a similar update to our low-level library.

Yes I meant you should change that in your layer :) Can you ping me when a new artifact is out with that change?

**Comment by mziccard** [comment]
`cloud-datastore-emulator-1.2.0.zip` seems to work fine, provided that you remove the extra `/datastore` from the endpoint. Any idea when this will be included in `gcloud`?

**Comment by eddavisson** [comment]
`datastore-v1-proto-client:1.1.0` will remove `/datastore`. That should be available in Maven in the next couple of hours.

The `gcloud` update will take a little longer. We're targeting some time next week.

**Comment by mziccard** [comment]
@eddavisson `cloud-datastore-emulator-1.2.0` is failing to run on Java7 with the following error:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/cloud/datastore/emulator/CloudDatastore : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```
This is usually a problem with code generation, can you look into it please? FYI previous version (`1.1.1`) used to work just fine.

**Comment by eddavisson** [comment]
I've re-uploaded a fixed version of the tool to GCS. Can you see if it works now?

**Comment by mziccard** [comment]
@eddavisson it works just fine now, thanks!
