### ISSUE TITLE
Allow CloudStorageFileSystemProvider without credentials

### ISSUE THREAD

**Issue by jean-philippe-martin** [GoogleCloudPlatform/gcloud-java#1188]
When using any NIO Filesystem provider, Java will enumerate them all and try to create them.

Our CloudStorageFileSystemProvider will throw an exception if there is no `GOOGLE_APPLICATION_CREDENTIALS` environment variable (because then it can't find credentials). This seems reasonable at first but here this means that even if someone is not using `gs://` at all, just by having our jar in the classpath they become unable to use *other* filesystem providers.

[This issue](https://github.com/broadinstitute/gatk/issues/2110) shows a concrete instance, with example.

This suggests we need to allow CloudStorageFileSystemProvider to be created without credentials. We can fail later, when the user tries to get a `CloudStorageFileSystem` instance.

Sounds good?

cc: @jart, @mziccard

**Comment by jart** [comment]
Sgtm

**Comment by mziccard** [comment]
> This suggests we need to allow CloudStorageFileSystemProvider to be created without credentials. We can fail later, when the user tries to get a CloudStorageFileSystem instance.

Sounds reasonable to me. Happy to review a PR :)

**Comment by jean-philippe-martin** [comment]
Thanks to you both! And @mziccard since you offered so kindly I assigned you to my pull request, #1189.

**Comment by mziccard** [comment]
This was fixed by #1189 thanks to @jean-philippe-martin.
