### ISSUE TITLE
Avoid downloading gcd.sh if cloud SDK is availble

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#123]
Cloud SDK now supports running a local datastore by invoking  `gcloud beta emulators datastore`.
If we detect that gcloud is available we should run the datastore using it rather than fetching/caching and invoking `gcd.sh`

**Comment by mziccard** [comment]
Having a look at this I noticed that `gcloud beta emulators datastore` runs the datastore with no `--allow_remote_shutdown` option and I could not find a way to provide it. This might be a problem for us as we use the `POST /_ah/admin/quit` API to shutdown the datastore emulator once the tests are run. 

Shall we ask for that option to be added to gcloud (It's a really small change)?

**Comment by jgeewax** [comment]
Yes, we should. @pcostell ?

**Comment by pcostell** [comment]
Yes we should -- I can file a bug internally, or someone can file a bug against the [gcloud SDK] (https://github.com/GoogleCloudPlatform/gcloud/issues). It wasn't left out intentionally, it just wasn't prioritized.

Also, you can work around this by using the gcd tool directly `$GCLOUD_PATH/platform/gcd/gcd.sh`

Something to consider -- it may be worth pinning the version of gcd you use for development. Otherwise, tests on one machine may act differently than tests on the other.

**Comment by mziccard** [comment]
Thanks @pcostell, I'll file a bug against [gcloud SDK](https://github.com/GoogleCloudPlatform/gcloud/issues) then.

I think the point of using `gcloud` was to let it handle `gcd.sh` install and update (and to avoid multiple downloads). But while the `--allow_remote_shutdown` gets added we can go for calling `gcd.sh` directly (`$GCLOUD_PATH/platform/gcd/gcd.sh`) if installed. Any thoughts @aozarov?

**Comment by pcostell** [comment]
Just a random note, I think you should just use --testing. I believe it includes --allow_remote_shutdown as well as a bunch of things designed to make unit testing easier.

**Comment by aozarov** [comment]
Yes, that sounds good (or we can try the `--testing` flag and see if that works).

However to @pcostell point, one benefit of the existing code is that LocalGcdHelper is pinned to a specific gcd version that is known to work with. I still think we should leverage gcloud SDK if exists but
we should find a way to verify that its local datastore version matches as well. @pcostell is there a way for us to do that?

**Comment by pcostell** [comment]
It looks like `gcloud version` lists which version of the emulator is in use and includes the API version.

**Comment by mziccard** [comment]
@pcostell Do you mean `--testing` as an option to `gcd.sh`? As far as I know it does not include `--allow_remote_shutdown`:
>   --testing
    Start the local Cloud Datastore in 'testing' mode. Equivalent to passing
    --consistency=1.0 and --store_on_disk=false and
    --store_index_configuration_on_disk=false.

@aozarov I run the tests with gcd v1beta2-3.0.0 and they are passing.

**Comment by aozarov** [comment]
> @aozarov I run the tests with gcd v1beta2-3.0.0 and they are passing.

Great, I was expecting that. I think the LocalGcdHelper needs to check that gcloud SDK gcd-emulator prefix is v1beta2 before deciding to use.

**Comment by pcostell** [comment]
@mziccard you're totally right, it isn't included. Perhaps we should consider including it.

**Comment by aozarov** [comment]
Fixed in #162
