### ISSUE TITLE
gcloud-java-storage pulls guava-jdk5

### ISSUE THREAD

**Issue by shun-fan** [GoogleCloudPlatform/gcloud-java#126]
When including gcloud-java-storage, it is necessary to exclude guava-jdk5 or else it will conflict with guava-18.0.jar. For some reason guava-jdk5 is being pulled by gcloud-java when apparently it shouldn't.

**Comment by ajkannan** [comment]
Looks like gcloud-java-storage's dependency on guava-jdk5 comes from here (exerpt from the dependency tree): 
com.google.apis:google-api-services-storage:jar:v1-rev33-1.20.0
      com.google.api-client:google-api-client:jar:1.20.0
            com.google.guava:guava-jdk5:jar:13.0

The Google-API-services-storage version may be a bit old (it's revision 33 out of 40)

**Comment by aozarov** [comment]
Fixed.
