### ISSUE TITLE
Icon for landing page

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#127]
We need an icon for the Java cloud platform landing page that is similar in style to the Node.js, Ruby, and Python pages.

**Comment by aozarov** [comment]
This [image] (https://gist.github.com/ryanseys/3ae962fe1c87d5b0cb02#file-logo-svg) was suggested but we need legal clearance.

**Comment by aozarov** [comment]
@jgeewax Do you have any insight about any legal issues regarding using this icon (or any other related - e.g. [Duke](https://www.google.com/search?q=java+duke+icon&espv=2&biw=1920&bih=1087&tbm=isch&tbo=u&source=univ&sa=X&ved=0CDgQ7AlqFQoTCLSy4Ju8uMcCFZA5iAodx7QIaQ&dpr=1) icons) ?

**Comment by jgeewax** [comment]
@jboynes : any thoughts on this? 

Also: http://www.oracle.com/us/technologies/java/java-licensing-logo-guidelines-1908204.pdf

**Comment by ludoch** [comment]
https://duke.kenai.com/ are BSD https://kenai.com/projects/duke/pages/Home

**Comment by jgeewax** [comment]
Awesome -- Duke it is :)

**Comment by ajkannan** [comment]
Fixed by #137
