### ISSUE TITLE
Creating javadoc for each module

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#128]
An aggregate Javadoc is created and linked in the website.  However, we do not generate and link specific Javadocs for the modules (i.e. gcloud-java-core, gcloud-java-datastore, etc).

**Comment by aozarov** [comment]
I wonder if it is possible to insert a static link per module to point to the aggregate javadoc in the desired package (as an alternative to duplicate generation)
