### ISSUE TITLE
Consider Jenkins instead of Travis

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#135]
Investigate whether Jenkins may work better for this project than Travis CI.

**Comment by jgeewax** [comment]
Any more background on why ? gcloud-python / gcloud-ruby / gcloud-node all use Travis pretty happily. :)

**Comment by ajkannan** [comment]
Jenkins was recently used to create Docker images for testing Managed VMs, and we thought it might be good to know why.  This issue is a pretty low priority; AFAIK, gcloud-java hasn't hit any big issues with Travis either, we just want to know more.

**Comment by mziccard** [comment]
This issue has been open for a while, I see no reason for moving to Jenkins and for the time being I believe it's better that all gcloud-* projects stick to the same CI. If we ever encounter issues with Travis or if you have strong point in favor of further investigation feel free to reopen this issue.
