### ISSUE TITLE
Travis times out when deploying website to gh-pages

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#140]
Maven's site-deploy plugin takes more than 20 minutes to push a new website to gh-pages.  As a result, Travis times out and does not push the website.  We should experiment with pushing the website to github using bash code rather than maven's plugin.

**Comment by jgeewax** [comment]
Yikes - that's absurdly long.. why would it take forever? Do we know ?

**Comment by ajkannan** [comment]
I think it's the number of files combined with the specific protocol that maven uses (wagon wheel protocol).  It's been an off and on problem for a while, but it seems to be getting worse as time goes on.

**Comment by aozarov** [comment]
Yes, this is an old and known issue (see https://github.com/github/maven-plugins/issues/27 and https://github.com/github/maven-plugins/issues/88) but recently it feels much worse for us (probably after we converted to modules which generates much more site information than before).

Workarounds include making Travis build the site locally (using stage) and then using git to commit it directly.

**Comment by mziccard** [comment]
Just to share my (never requested :smile:) thoughts on the matter. I think that building the site in Travis with `maven site` (should do it) and then committing with git is the best solution considering that `gh-pages` branch is cloned anyway (lines 19-34 of `after_success.sh`) to update the "latest" landing page.

**Comment by ajkannan** [comment]
Closed by #151
