### ISSUE TITLE
populate "force" in allocateId requests once datasore api expose it.

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#16]
see b/18594027

**Comment by aozarov** [comment]
I think we can close that as Datastore v1beta3 seems to remove "force" completely.
Is that right @ajkannan ?

**Comment by ajkannan** [comment]
Yup, they've removed force completely.  In my understanding, it could be added back in the future, but that's unclear.  We can reopen this issue if it ever does get added back.
