### ISSUE TITLE
Datastore tests not running on Windows

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#163]
Running datastore tests on Windows Server 2012 leads causes the following error:
> java.io.IOException: Cannot run program "cmd": NULL: (The filename, directory name, or volume label syntax is incorrect)

Caused by the `NULL:` at line:
https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/test/java/com/google/gcloud/datastore/LocalGcdHelper.java#L171

`NUL:` (with one `L`) seems to be a valid null device across Windows versions.

@aozarov shall we close this with #162 (as soon as it's ready) or create a dedicated PR?

**Comment by aozarov** [comment]
Strange, we did test it on Windows before but maybe this was added later.

Yes, @mziccard thanks for finding it. I think fixing it with #162 is fine.

**Comment by aozarov** [comment]
Fixed in #162
