### ISSUE TITLE
NPE From some Storage methods

### ISSUE THREAD

**Issue by simon-temple** [GoogleCloudPlatform/gcloud-java#174]
For example the following calls when listing a bucket that is empty or getting an item from a bucket that exists but the item does not:
```java
    storage.list( bucketName )
    storage.get( bucketName, itemName )
```
The NPE is generated from the Preconditions class called via transform() in the Iterables class:
```java
public static <T> T checkNotNull(T reference) {
        if(reference == null) {
            throw new NullPointerException();
        } else {
            return reference;
        }
    }
```
It would be nicer to return a null to the caller perhaps.  wdyt?

**Comment by mziccard** [comment]
Hi @simon-temple, thanks for catching this!
I was able to reproduce the error with `storage.list("non-existing-bucket")` while `storage.get("existing-bucket", "non-existing-blob")` returns null as expected. Could you double check this please?

**Comment by mziccard** [comment]
This problem also occurs when listing buckets if none exists (`storage.list()`).

**Comment by simon-temple** [comment]
Here is a stack trace of an attempt to get() a none existent blob from an existing bucket:
```
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at com.google.gcloud.storage.BlobInfo$Builder.name(BlobInfo.java:125)
	at com.google.gcloud.storage.BlobInfo.builder(BlobInfo.java:390)
	at com.google.gcloud.storage.BlobInfo.of(BlobInfo.java:382)
	at com.google.gcloud.storage.StorageImpl.get(StorageImpl.java:149)
```

**Comment by simon-temple** [comment]
Could you also check:
```java
bucketInfo = storage.get( "none-existent-bucket" );
```
I believe this will also throw a NPE.

**Comment by mziccard** [comment]
Thanks for checking. The stack trace you posted looks more like you are doing something like
```
get("existing-bucket", null)
```
Could you check that the blob name you are passing is actually not null?

**Comment by simon-temple** [comment]
You are correct.  My bad...sorry!

I am calling get("existing-bucket", null) and I shouldn't; but that's my problem :-)

Thanks for your help.

**Comment by mziccard** [comment]
Nothing to be sorry about. The other problems you spotted when listing an empty bucket or listing buckets when none exists are our fault so let me thank you for catching them :)
I'll keep this issue open until I fix them (should be real soon).

**Comment by simon-temple** [comment]
Thank you for the quick turnaround.  Does this project have a SNAPSHOT repo?  I'd like to run some tests with the latest/fixed version if possible.  Maybe I need to clone the project and rebuild locally?

Any idea when the next release will be available?

**Comment by mziccard** [comment]
Yes, we are publishing snapshot to Sonatype snapshots repository: 
> https://oss.sonatype.org/content/repositories/snapshots/

Current snapshot is `0.0.8-SNAPSHOT`. Be aware that PR #183 is not merged yet so it's not part of the snapshot (i.e. you'll still have this issue). I hope we'll manage to merge it by the end of the day.

@aozarov should have more info on the plans for next release.

**Comment by aozarov** [comment]
As you can see `Storage` is still work in progress (and that is why it is not yet mentioned in list of supported services in the [README.md](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/README.md)). 

Snapshots should be pushed automatically (triggered by Travis), so once this change is pushed it should not take long before it appears [here](https://oss.sonatype.org/content/repositories/snapshots/com/google/gcloud/gcloud-java/0.0.8-SNAPSHOT/).
