### ISSUE TITLE
FIgure out the work needed for PubSub service

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#18]

**Comment by garrettjonesgoogle** [comment]
Out of curiosity, what would define this issue as done?

**Comment by aozarov** [comment]
So far we treated this kind of an issue as "Add support for service X".

We kept this misleading title for consistency though I think we should stop doing that for future services and be more specific (or use this one for only getting the proposed API approved).

**Comment by mziccard** [comment]
This was closed by #1085
