### ISSUE TITLE
Should functional blob and bucket operations enforce metageneration match upon updates

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#194]
This topic was also discussed in #171.

Currently the functional blob and bucket pin to their metadata and provide the user with the option of enforcing metadata version check in updates operation. However this check is not triggered by default.

An alternative to what we have now is to enforce the version check by default and to provide options to disable the check instead.

**Comment by aozarov** [comment]
My preference is to keep the existing way (no enforcement by default but have an option to support such check).

**Comment by mziccard** [comment]
I am +1 for not checking by default and adding an option.

**Comment by aozarov** [comment]
@mziccard Just to make sure I understand your preference.
Is your preference to keep the existing way or are you suggesting to *add* a new option?

**Comment by mziccard** [comment]
@aozarov I want to keep `update` as it is (no enforment by default). If we want we can add support for generation checks by allowing something like:

```java
blob.update(newInfo, 
  UpdateOptions.generationMatch(), UpdateOptions.metagenerationMatch());
```

**Comment by aozarov** [comment]
Ok, thanks for making it clear.

Isn't that already supported?

```java
blob.update(newInfo,
    BlobTargetOption.generationMatch(), BlobTargetOptions.metagenerationMatch());
```

**Comment by mziccard** [comment]
Yeah my bad :) Then it's ok how it is for me!

**Comment by mziccard** [comment]
This has been open for a while. As I already said I believe that the way we do these checks now is ok and consistent with other uses of `generationMatch()` and `metagenerationMatch()` options. I am closing this. Feel free to reopen if you believe we should give this more thoughts.
