### ISSUE TITLE
Storage.copy not failing on source (meta)generation mismatch

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#195]
The following code:
```java
Storage.CopyRequest req = new Storage.CopyRequest.Builder()
  .source(bucket, sourceBlobName)
  .target(destinationBlob)
  .sourceOptions(Storage.BlobSourceOption.generationMatch(42L))
  .build();
storage.copy(req);
```
Is not throwing an exception if the source blob generation is not 42.

**Comment by jgeewax** [comment]
Is this an issue with the server-side stuff not returning a fail? (Is it
picking "the closest one to 42"?) Or is this in our code?

**Comment by mziccard** [comment]
@jgeewax It's an issue with our code, we are not sending the correct parameters, I am about to submit a fix. Server-side stuff is checking for exact match.
