### ISSUE TITLE
drop Datastore StructuredQuery#Aggregate as it is going away

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#24]

**Comment by pcostell** [comment]
Given in API: projection A, B, C and distinct on (A, B)
Produces proto:  group by (A, B) projection (A, B, FIRST(C))
Remove from API group by and aggregation. Change group by to distinct. Note that this should support both distinct(properties) and just distinct:
SELECT DISTINCT A, B FROM K implies:
SELECT DISTINCT ON(A, B) A, B FROM K

**Comment by ajkannan** [comment]
Closing this as StructuredQuery#Aggregate was removed in the transition to v1beta3.
