### ISSUE TITLE
BlobWriteChannel CRC32C and MD5 hash mismatch error

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#267]
The following code:
```java
BlobId blobId = BlobId.of("bucket", "blob_name");
BlobInfo blobInfo = BlobInfo.builder(blobId).contentType("test/plain").build();
storage.create(blobInfo, "Hello, Cloud Storage!".getBytes(UTF_8));
BlobInfo updatedBlobInfo = storage.get(blobId);
WritableByteChannel channel = storage.writer(updatedBlobInfo);
channel.write(ByteBuffer.wrap("Updated content".getBytes(UTF_8)));
channel.close();
```
causes an error:
> Caused by: com.google.gcloud.storage.StorageException: 400 Bad Request
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Provided CRC32C \"IgKckQ==\" doesn't match calculated CRC32C \"c5cgUw==\"."
   },
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Provided MD5 hash \"paCw+9t7LhjISSAPBaeazA==\" doesn't match calculated MD5 hash \"SFCAEvYjPzpCjkKQr6MGGg==\"."
   }
  ],
  "code": 400,
  "message": "Provided CRC32C \"IgKckQ==\" doesn't match calculated CRC32C \"c5cgUw==\"."
 }
}

If a stale `BlobInfo` object is passed to `storage.writer(blobInfo)` instead:
```java
// ...
BlobInfo blobInfo = BlobInfo.builder(blobId).contentType("test/plain").build();
storage.create(blobInfo, "Hello, Cloud Storage!".getBytes(UTF_8));
WritableByteChannel channel = storage.writer(blobInfo);
channel.write(ByteBuffer.wrap("Updated content".getBytes(UTF_8)));
channel.close();
```
No error occurs.

It seems to me that if a "complete" `StorageObject` is passed to `DefaultStorageRpc.open` then its `md5Hash` and `crc32c` fields are used to request the upload id (see [this](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-storage/src/main/java/com/google/gcloud/spi/DefaultStorageRpc.java#L495) line). At the end of the upload if that data do not match with the uploaded one the whole upload fails. 
Do you think this is a desirable default behavior? 
I think it is not, I would rather add some options to `storage.writer(...)` to allow users to explicitly choose to check `md5Hash` and `crc32c` if they have already computed them and put them into the `BlobInfo` object (i.e. if they know what they're doing).
Thoughts?

**Comment by aozarov** [comment]
Good catch!

Yes. GCS does use consider `crc32c` and `md5Hash` for [insert operation](https://cloud.google.com/storage/docs/json_api/v1/objects/insert) and use it to validate
the content upon completion.

I think this is a tricky one as one might not expect it, like in the usage pattern you described.
However, some users may want to take advantage of this feature in order to verify the uploads.

We could document this behavior in the Java doc (and add a code snippet showing how to clear the 2 fields if BlobInfo was not manually constructed and the validation is undesired) but I think this is even
trickier when one is using `Blob.writer`...

Another way to deal with it can be to have a separate set of options to writer.
By default, we will ignore the 2 fields unless requested via an option.

Thoughts?

/cc @BrandonY

**Comment by aozarov** [comment]
Actually, this issue also applied to `create` methods.
In the case of `create` we should probably "reset" the md5 and crc to reflect the `byte[]` or empty but
we still have an issue with the newly added method that accepts an `InputStream`.
Maybe that create should also use the `write` options...

**Comment by aozarov** [comment]
Another option (not sure if I like it that much) is to have a "special" method on `BlobInfo` and `Blob` that is basically a syntactic sure for `toBuilder().md5(null).crc32c(null).build()`.

Any other suggestions we welcomed!

**Comment by mziccard** [comment]
My preferred option is to handle this with options:D
I would add a `BlobWriteOptions` which has the same static methods as `BlobTargetOptions` and also:
```java
md5HashMatch()
crc32cMatch()
```
And we make `create` and `write` accept a `BlobWriteOptions` instead of `BlobTargetOptions`. If those options are specified we pass on `md5Hash` and `crc32c` to RPC's `StorageObject`, otherwhise we set them to null (to prevent the error this issue refers to).
This seems to me the "less unexpected" behaviour. But I am open for suggestions!

**Comment by aozarov** [comment]
Yes, that is my prefered option too (though I would also suggest to keep the BlobWriteOptions and reset the crc32c and md5 for the empty `create` and the `create` with `byte[]`).

**Comment by mziccard** [comment]
Makes perfectly sense
