### ISSUE TITLE
Write tests for LocalGcdHelper and RemoteGcsHelper

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#268]
Since these classes were moved into production, it'd be good to write tests for these classes.  Users may have more expectations for this code since it was moved to the production package.  Also, our test coverage may be limited without these tests.

**Comment by mziccard** [comment]
@ajkannan Makes sense, if you want I would be happy to help unit-testing RemoteGcsHelper.

**Comment by ajkannan** [comment]
That'd be great @mziccard, thanks!
