### ISSUE TITLE
Fix int casting of lastBytePos in DefaultStorageRpc.read

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#290]
This depends on https://github.com/google/google-api-java-client/issues/937. `MediaHttpDownloader.setContentRange` takes `firstBytePos` as a long while `lastBytePos` as an int. As soon as this gets fixed we need to remove `int` casting.

**Comment by aozarov** [comment]
While google/google-api-java-client#937 was not fixed yet we no longer use the `MediaHttpDownloader` and therefore this is not an issue for us anymore.

**Comment by Venkata96** [comment]
@aozarov What do we use instead of MediaHttpDownloader? How do we download a chunk

**Comment by aozarov** [comment]
see the [associate change](https://github.com/GoogleCloudPlatforme/google-cloud-java/pull/390/files#diff-e1d1a71790d1d8ec430041dc43d5373f) or [current code](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/ab102630bb3db277a0810c44b05100114e128e44/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java#L488).
