### ISSUE TITLE
Show how to add gcloud-java as a dependency in gradle and sbt

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#295]
We already show this [here](http://googlecloudplatform.github.io/gcloud-java/0.0.10/dependency-info.html) but it's quite hidden. 
What do you think about adding this information to the README and to the landing page (as a tabbed view?)?

I know this is something that a user can construct from maven's dependency but we could make it easier.

**Comment by jgeewax** [comment]
Hmm.. I don't see gradle on that list?

**Comment by mziccard** [comment]
That page is autogenerated with `mvn site` that seems not to provide info for `gradle`.

Now that I notice, that page shows instructions on how to include the poms artifact, which is weird and not what we want.

**Comment by aozarov** [comment]
Fixed by #327
