### ISSUE TITLE
Create an example site and reference it from the main site

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#31]
e.g. https://github.com/GoogleCloudPlatform/gcloud-python -> https://github.com/GoogleCloudPlatform/gcloud-python-expenses-demo

**Comment by jboynes** [comment]
Suggested name for new repo: GoogleCloudPlatform/gcloud-java-examples

**Comment by aozarov** [comment]
SGTM

**Comment by jboynes** [comment]
Repo created. PR for initial seed https://github.com/GoogleCloudPlatform/gcloud-java-examples/pull/1

**Comment by aozarov** [comment]
Note that after change #74 examples are in a separate module and no longer part of the client artifacts.

**Comment by aozarov** [comment]
I think we should keep the samples module as part of this project (similar to [aws] (https://github.com/aws/aws-sdk-java/tree/master/src/samples)) and use this issue for tracking the progress on building an example app[s] using gcloud-java (similar to [gcloud-python-expenses-demo](
https://github.com/GoogleCloudPlatform/gcloud-python-expenses-demo)).

**Comment by aozarov** [comment]
@ludoch looks like GoogleCloudPlatform/gcloud-java-examples got deleted.

Do you mind to re-create it by [copying](https://help.github.com/articles/importing-a-git-repository-using-the-command-line/) your examples?

**Comment by ajkannan** [comment]
Update on this issue: the [example site](https://github.com/GoogleCloudPlatform/gcloud-java-examples/) is back up with a preliminary example thanks to Ludo.  I will be working on expanding it/adding docs/adding links to it form other sites.

**Comment by ajkannan** [comment]
Closing this issue.  gcloud-java samples should go in [java-docs-samples](https://github.com/GoogleCloudPlatform/java-docs-samples), and we have a link to a sample app from our website.  We will add more sample apps as they get created.
