### ISSUE TITLE
Provide a convenient way to get all results from a com.google.gcloud.Page

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#330]
In cases when paging between different requests is not necessary (all results are consumed in the same request/thread) a common usage-pattern would be as such:
```java
Page<V> page = .... get first page
while (page != null) {
  for (V v : page.values()) {
    ...do something...
  }
   page = page.nextPage();
}
```

or
```java
Page<V> page = .... get first page
do {
  for (V v : page.values()) {
    ...do something...
  }
  page = page.nextPage();
} while (page != null);
```

To avoid this boilerplate code It would be nice to add to the `Page` class a method to return
an `Iterator` for all the results (and let that Iterator do the paging).

Some options:

(1) add a static method such as Page.iterateAll(page)
(2) an instance method such as `page.allValues()` or `page.iterateAll()` or `page.fetchAll()`

Any preference or other suggestions?

**Comment by mziccard** [comment]
I would prefer an instance method. I would also not use `allValues` as we alredy have a `values`  method that returns `Iterable` instead. My preference is `iterateAll` or simply `iterator` provided that we document what the method does.

**Comment by aozarov** [comment]
Sure, I like `iterateAll` better than `iterator` for being more explicit.
