### ISSUE TITLE
We should mention GOOGLE_APPLICATION_CREDENTIALS in the Authentication section.

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#331]
The main gcloud-java [README.md](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/README.md) contains an authentication section however this section does not
mention the option of using the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to point to a key file.

@mziccard I now wonder if we need the `GCLOUD_TESTS_KEY` and `GCLOUD_TESTS_PROJECT_ID` in the `RemoteGcsHelper` as `GOOGLE_APPLICATION_CREDENTIALS` could be used instead of the former and `GCLOUD_PROJECT` could be used instead of the latter.

**Comment by mziccard** [comment]
@aozarov When I introduced those 2 variables I took inspiration from gcloud-node. The rationale is that to run integration tests the user must know what he is doing and he has to pick the right credentials/projectId before running tests as he is going to be billed for them.

For instance I have a personal account on Google Cloud whose credentials are set in `GOOGLE_APPLICATION_CREDENTIALS` but I use different whitelisted credentials/project to run integration tests.

**Comment by jgeewax** [comment]
I'm with @aozarov on this one -- having separate env vars for tests seems a
bit off.

Running tests should look something like

```bash
$ cat run_test.sh
GOOGLE_APPLICATION_CREDENTIALS=test.json mvn test
```

right?

**Comment by aozarov** [comment]
Right, it should not be a problem to temporarily override environment variable.

**Comment by aozarov** [comment]
I created #335 for tracking the `RemoteGcsHelper` specific keys issue.
