### ISSUE TITLE
Remove checks for old-style Compute/App Engine auth credentials

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#334]
Because [this bug is resolved](https://github.com/google/google-auth-library-java/issues/2), we can simplify our code that attempts to locate default credentials.  The [Application Default Credentials](https://developers.google.com/identity/protocols/application-default-credentials) does this work for us now.

**Comment by aozarov** [comment]
Both Auth.AppEngineAuthCredentials and Auth.ComputeEngineAuthCredentials may no longer be necessary but we should verify it by running it an application using gcloud-java on AE (dev_app and prod) and CE.

**Comment by ajkannan** [comment]
Related to this issue
-- We should update the README once the order of auth lookup is updated.
-- We should standardize the order of project ID lookup based on the auth lookup order.  This requires modifying the code and the README's project ID section
