### ISSUE TITLE
I can not use the tag "gcloud-java" in StackOverflow when I ask a question

### ISSUE THREAD

**Issue by lascarayf** [GoogleCloudPlatform/gcloud-java#338]
This link http://stackoverflow.com/questions/tagged/gcloud-java has cero questions because no one can use the tag "gcloud-java"

**Comment by mziccard** [comment]
@lascarayf thanks for your interest!

To [create a tag](http://stackoverflow.com/help/privileges/create-tags) a user must have at least 1500 reputation.

I also know that tags can be sponsored: [gcloud-ruby](http://stackoverflow.com/tags/gcloud-ruby/info) seems not to be sponsored while [gcloud-node](http://stackoverflow.com/tags/gcloud-node/info) is sponsored.
I suspect that to sponsor a tag it must exist first (i.e. it must have been created by a user). @jgeewax do you have some more information on this?

@lascarayf if you created a question on gcloud-java I might be able to create the tag myself.

**Comment by aozarov** [comment]
@jgeewax are you creating one?

**Comment by jgeewax** [comment]
Yep - asking for a sponsored tag today. If you have a question I can tag
with it, let me know as that'd be helpful.

**Comment by aozarov** [comment]
@jgeewax can we tag [this](http://stackoverflow.com/questions/34070065/google-cloud-java-client-library-not-compiling-through-gradle) with gcloud-java?

**Comment by jgeewax** [comment]
Done.

**Comment by aozarov** [comment]
Great, I think we can mark it as [fixed](http://stackoverflow.com/questions/tagged/gcloud-java).
