### ISSUE TITLE
in the README the datastore sample does not compile.

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/gcloud-java#342]
For example, Datastore datastore = DatastoreOptions.getDefaultInstance().service();
does not seem to work with 0.0.10

**Comment by ajkannan** [comment]
Yes, the README examples got updated too soon.  This example will work once we release version 0.0.11, which should be coming very soon (pending some testing in core).  The old way should still work, for example: 

`StorageOptions options = StorageOptions.builder().projectId("my_project_id").build();
 Storage storage = StorageFactory.instance().get(options);`

**Comment by ajkannan** [comment]
Also the javadoc (available on the [website](http://googlecloudplatform.github.io/gcloud-java/0.0.10/apidocs/index.html) and also packaged with version 0.0.10) should have examples that are in sync with the release version.

**Comment by ludoch** [comment]
Got it, thanks!

**Comment by aozarov** [comment]
@ajkannan just released 0.0.11 so maven should be consistent with site again.

**Comment by ludoch** [comment]
0.0.11 does not work with:
Datastore datastore = DatastoreOptions.getDefaultInstance().service();

**Comment by mziccard** [comment]
@ludoch Sorry for this, the method `getDefaultInstance` is not part of the `DatastoreOptions` interface, I don't know how it happened to be in the README. To get a Datastore service instance with default options try:
```java
Datastore datastore = DatastoreOptions.builder().build().service();
```
I'll take care of fixing this, either by adding the `getDefaultInstance` method or by updating the READMEs

**Comment by mziccard** [comment]
@ludoch In #357 we add back a `defaultInstance` method to `StorageOptions` and `DatastoreOptions` and update both READMEs and website's landing page (will be available on the next release).
Do you think we can close this?

**Comment by aozarov** [comment]
0.0.12 which includes adding back the `defaultInstance` methods is out but I think we need to merge #389 before closing this issue.

**Comment by mziccard** [comment]
#357 and #389 are merged so I am closing this. Feel free to reopen it if need be.
