### ISSUE TITLE
We should better document the Storage API

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#351]
Feedback from @mfschwartz

Are you planning to flesh out all the javadoc?  These classes are full of methods and fields with no javadoc. That doesn’t seem adequate for a public API. Even someone (such as myself) already familiar with other GCS APIs won’t know what to make of some of your classes (e.g., what’s a BlobSourceOption?), and someone not familiar with the other GCS APIs would have to read those other APIs’ documentation to figure out what they can specify for things like cache-control, ACL fields, etc. Also, in places where you re-model abstractions (e.g., replacing LifecycleConfig with DeleteRule), someone not really knowledgeable about GCS would have a hard time understanding what this API is for with the minimal javadoc currently present.

Related note: The fact that you remodel abstractions makes it harder for someone to know where to go for documentation about details like whether we have any SLA guarantees for lifecycle management operations, etc. I think it’s fine to re-model abstractions but I think your documentation needs to let users find out the more detailed information like this that we have documented elsewhere.

**Comment by aozarov** [comment]
@mziccard do you mind to take this issue?

**Comment by mziccard** [comment]
Closed with #355 and #356
