### ISSUE TITLE
We should include generation as part of the BlobId.

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#363]
And we should use that generation (if supplied) in applicable operations such as delete, compose, copy (and use the google-api-client "generation" field).

Also, that means that we need to change `BlobSourceOption` and `BlobGetOption` `generationMatch` and `generationNotMatch` to be based on the value given in `BlobId`.

**Comment by mziccard** [comment]
Fixed with #366
