### ISSUE TITLE
Update gh-pages landing page to look like gcloud-node?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-java#4]
Will Java developers be put off if the landing page looks like this?

Landing page (for reference) is here: http://googlecloudplatform.github.io/gcloud-node/#/

**Comment by aozarov** [comment]
No, it does look good and structured well however unless we really want uniformity with the look and feel of all our docs across the languages (hence docs are not "idiomatic") I would expect Java people to feel more comfortable with a structure that they are already familiar with. Currently Java gh-pages are generated by maven and their look and feel is typical for Java projects in the maven repository.

**Comment by jgeewax** [comment]
Would you be against the landing page being the standard one that's all pretty, and then having a link into the Maven generated docs ? 

(ie, "Maven docs" being one of the links in the white bar below the blue ?)

**Comment by aozarov** [comment]
No, but I don't necessary think "duplication" in docs saying similar (or same) things is a great idea (especially when they get out of sync). issue #5 suggests a detailed structure for README so that means 3 places that will overlap with some of their information.

**Comment by ajkannan** [comment]
Closed by #125
