### ISSUE TITLE
Use pubsub fake written by the pubsub team instead of LocalPublisherImpl

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/gcloud-java#400]
It isn't available in open source quite yet.

**Comment by aozarov** [comment]
We could use this in the meantime: https://pantheon.corp.google.com/storage/browser/pubsub/tools/

**Comment by garrettjonesgoogle** [comment]
here is the LocalPublisherImpl class: https://github.com/GoogleCloudPlatform/gcloud-java/blob/pubsub-alpha/gcloud-java-pubsub/src/main/java/com/google/gcloud/pubsub/spi/testing/LocalPublisherImpl.java
