### ISSUE TITLE
DatastoreExample does a put, but does not do the get to retrieve it

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/gcloud-java#41]
DatastoreExample does a put, but does not call the get to retrieve it:-)

**Comment by ludoch** [comment]
Also, not sure we do a     builder.set("f", 30);
What is f in the example?

**Comment by ludoch** [comment]
I think we should replace 
    System.out.println("Going to modify entity: " + entity);
    Entity.Builder builder = Entity.builder(entity);
    builder.set("f", 30);
    datastore.put(entity);
with
    System.out.println("Going to modify entity: " + entity);
    Entity.Builder builder = Entity.builder(entity);
    entity = builder.set("age", 40).build();  //set Age to 40!!!
    datastore.put(entity);

**Comment by ludoch** [comment]
Finally the last part of the example:
    System.out.println("Trying again to get the entity by its key!");
    key = Key.builder(dataset, "Person", "Jimmy").build();
    System.out.println("Got entity: " + entity);

does nothing with the key, so the entity is not really retrieved and just go the value from the last update.

I guess we need a full CRUD example, with a possible query example as well.

**Comment by aozarov** [comment]
I changed the exampls to demonstrate a full CRUD and usage of the two types of queries.
