### ISSUE TITLE
blobInfo.toBuilder().build() is not equal to blobInfo

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#415]
We have this situation:
```java
BlobInfo blobInfo = BlobInfo.builder(BlobId.of("b", "n")).build();
assertEquals(blobInfo, blobInfo.toBuilder().build()); // This fails!
```
This is due to the fact that `toBuilder` uses builder's setters that initialize (some of them) fields to `Data.nullOf()` if `null` is passed. This can be fixed by checking for `null` before calling setters in `toBuilder()`.

**Comment by aozarov** [comment]
Good catch. How about adding to `BlobInfo.Builder` a constructor that gets `BlobInfo` and copy the fields value directly? We could also add a static builder method that accepts `BlobInfo`...

**Comment by mziccard** [comment]
Adding a constructor to the builder that takes `BlobInfo` makes sense to me.

**Comment by eamonnmcmanus** [comment]
Have you considered using AutoValue here? It seems as if it would simplify BlobInfo greatly. It would also have a much more performant `equals`

**Comment by aozarov** [comment]
I think using `AutoValue` is a fine idea that we should considered but tracked and dealt with separately.
Created #418
