### ISSUE TITLE
Run unit tests for non-master branch PRs

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#420]
Right now, we only run unit tests for PRs that are on the master branch.  We should run the unit tests.  We can optionally include a coverage report, but since PRs in other branches tend to be "work in progress" it's not as vital.

**Comment by mziccard** [comment]
+1 to this! I know that you are very busy with resource manager and authentication changes so if you want to offload this just tell me:)

**Comment by ajkannan** [comment]
@mziccard if you have time today go for it.  I would probably get to it on Monday or Tuesday, so no pressure to take it if you're busy.  I haven't started anything yet on this issue.
