### ISSUE TITLE
Should we repackage the spi layer?

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#422]
Right now all services' spi layers are bundled into one package (`com.google.gcloud.spi`).  While this provides the convenience of separating the spi javadoc from the api javadoc, the one package may not make sense as we add more and more services.

**Comment by mziccard** [comment]
@ajkannan Could you please add more details on this? Are you suggesting to add one `spi` package per-service?

**Comment by ajkannan** [comment]
Yes; we could make one spi package per service, and make sure that they get packaged separately from the api layer services

**Comment by mziccard** [comment]
Reopening this. Should be closed as soon as this is also applied to compute.

**Comment by mziccard** [comment]
Closed with #742 and #901
