### ISSUE TITLE
gcloud-java not compiling with gradle

### ISSUE THREAD

**Issue by koleshop** [GoogleCloudPlatform/gcloud-java#436]
I'm using this line in gradle:
**compile 'com.google.gcloud:gcloud-java:jar:0.1.0'**

It's giving compiling error:
**Error:(35, 13) Failed to resolve: com.google.gcloud:gcloud-java:jar**

I've also created a stackoverflow question
http://goo.gl/9nOA4a

**Comment by mziccard** [comment]
Hi @koleshop thanks for spotting this. Could you give a try to:
```groovy
compile 'com.google.gcloud:gcloud-java:0.1.0'
```

**Comment by koleshop** [comment]
thanks!
it solved the problem

**Comment by mziccard** [comment]
Thanks to you for spotting the error. If you ever have any other issue with gcloud-java please let us know, we are glad to receive some feedbak.
 
PS: I reopened the issue, I'll close this as soon as we fix the error in our [README](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/README.md)
