### ISSUE TITLE
Tie BigQueryError to BigQueryException

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#444]
`BigQueryError`s are returned as part of a job state, as the result of a [query operation](https://cloud.google.com/bigquery/docs/reference/v2/jobs/query) and as a response to [insert all](https://cloud.google.com/bigquery/docs/reference/v2/tabledata/insertAll). In all the above cases a `BigQueryException` is not thrown.

When a request fails the service returns an error in the form:
```json
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "Not found: Table gcloud-devel:dataset.view"
   }
  ],
  "code": 404,
  "message": "Not found: Table gcloud-devel:dataset.view"
 }
}
```
So we could add a `BigQueryError` field to `BigQueryException` containing the error that caused the exception.

**Comment by aozarov** [comment]
:+1:
