### ISSUE TITLE
Remove StreamingBuffer filed from ExternalTable

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#447]
Streaming inserts to an external table is not supported, we should remove the `StreamingBuffer` field.

**Comment by aozarov** [comment]
And I assume we can move `StreamingBuffer` from `BaseTableInfo` to `TableInfo`?

**Comment by mziccard** [comment]
@aozarov yep

**Comment by mziccard** [comment]
Fixed with #482
