### ISSUE TITLE
Add a common interface for resource field enums

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#456]
We should consider creating an interface for all field enums (e.g. `DatasetField` in gcloud-java-bigquery and`BlobField` in gcloud-java-storage).
```java
interface ResourceField {
  String selector();
}
```
Selector's creation code (at least part of it) should be moved to a common static method.

**Comment by aozarov** [comment]
For background see [this](https://github.com/GoogleCloudPlatform/gcloud-java/pull/454#discussion_r47676271).

**Comment by mziccard** [comment]
Fixed with #807

**Comment by aozarov** [comment]
@mziccard I just wonder if we should keep this one open until you also apply the fix to compute?

**Comment by mziccard** [comment]
Keeping this open until it's fixed in compute

**Comment by mziccard** [comment]
This was fixed for compute in #970
