### ISSUE TITLE
Should we set a default retry strategy?

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#458]
Right now, the default setting when creating a service is to not retry at all.  Should we instead set a default retry strategy?  While retrying is important for some services, setting the default to retry may increase the costs for users.  

Alternatively, we could have two shortcut methods to get the options, `defaultInstanceNoRetries` and `defaultInstanceWithRetries`

**Comment by aozarov** [comment]
And if we don't change the default we should highly encourage it in our documentation **and** examples.

**Comment by aozarov** [comment]
Considering what we see in integration tests and the added value of retry handling my vote would
be to use the default in the default settings **and** document that we are using a retry handling which could be disable by setting `RetryParams.noRetries()`.

@mziccard what do you think?

**Comment by mziccard** [comment]
Yes I agree we should retry by default given the amount of requests we see fail in ITs

**Comment by ajkannan** [comment]
Great, I'll assign this issue to myself then.
