### ISSUE TITLE
Delete Google-internal path from documentation

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/gcloud-java#471]
Some doc comments pulled from protobuf has references to file paths used at Google. These should go away as Logging API matures, and we will regenerate the libraries.

- [x] gcloud-java-logging/src/main/java/com/google/gcloud/logging/spi/v2/ConfigServiceV2Api.java
- [x] gcloud-java-logging/src/main/java/com/google/gcloud/logging/spi/v2/MetricsServiceV2Api.java

**Comment by mziccard** [comment]
This issue is fixed since #767
