### ISSUE TITLE
Make DatastoreException message more informative

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#478]
In `DefaultDatastoreRpc.translate(DatastoreException exception)`, we lose helpful error messages because we only throw a DatastoreRpcException based on the associated `Reason`.  For example, in a malformed query request, the user gets an exception with the message "Invalid request".  The original exception thrown and translated by the method mentioned above may include a message such as "must specify all group by orderings before any non group by orderings", which is far more helpful for the user.

**Comment by aozarov** [comment]
:+1: Could be handled by #438.

**Comment by aozarov** [comment]
We could also set root cause to the original exception (should be useful even after #438).
