### ISSUE TITLE
Add format parameter to ExtractJobInfo and LoadJobInfo factory methods

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#489]
We have several `of` factory methods for `ExtractJobInfo` and `LoadJobInfo`. All take the id of the table involved and one or more GCS URIs. We should probably add a `format` parameter to make them more flexible. Thoughts?

**Comment by aozarov** [comment]
Sure, but we should consider that this is only a syntactic sugar for `builder` that avoids the need for invoking `build()` for *common*  construction patterns.
Therefore I think we need to verify if that is indeed a common construction pattern...

/cc @jtigani
