### ISSUE TITLE
Make methods that return BaseTableInfo or JobInfo generic

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#499]
The following method in `BigQuery` should be made generic:
- `BaseTableInfo create(BaseTableInfo table, TableOption... options)`
- `BaseTableInfo update(BaseTableInfo table, TableOption... options)`
- `BaseTableInfo getTable(String datasetId, String tableId, TableOption... options)`
- `BaseTableInfo getTable(TableId tableId, TableOption... options)`
- `JobInfo create(JobInfo job, JobOption... options)`
- `JobInfo getJob(String jobId, JobOption... options)`
- `JobInfo getJob(JobId jobId, JobOption... options)`

For instance:
```java
<T extends BaseTableInfo> T create(T table, TableOption... options) throws BigQueryException;
```

**Comment by aozarov** [comment]
Fixed by #500
