### ISSUE TITLE
Speed up ResourceManager tests on Travis

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#504]
Tests that use the mock resource manager helper take a relatively long time to complete on Travis.  `LocalResourceManagerHelperTest` takes ~100 seconds and `ResourceManagerImplTest` takes ~45 seconds.  When running locally, these tests only tend to take 3-5 seconds.  This is likely because the `HttpServer` library used for the mock spins up threads and also uses sockets, and Travis probably handles these operations more slowly.  We should think of a way to speed up these tests.

**Comment by mziccard** [comment]
Not sure if this is a pattern but the two tests seem to take much less in oraclejdk8 builds:
- `LocalResourceManagerHelperTest` ~ 5 sec
- `ResourceManagerImplTest ` ~ 3 sec

**Comment by ajkannan** [comment]
Interesting, the faster test runs in version 8 build seem to be a trend.  Perhaps related, `ConcurrentHashMap` (used by the mock) seems to have radically changed in implementation between version 7 and 8.  There must be a lot of lock contention if this is indeed the cause.

**Comment by aozarov** [comment]
see [this](http://stackoverflow.com/questions/15235075/1s-delay-in-httpserver-since-java-7).

A suggested workaround to add  `exchange.getResponseHeaders().add("Connection", "close");`
just before `exchange.sendResponseHeaders` (line 189) seems to make it much faster.
