### ISSUE TITLE
Configure Travis to automatically push new tags to Maven

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-java#51]
Logic here is that we wouldn't want Maven lagging behind the GH repository.

I don't know if it's standard to have a nightly (or master) type build available on Maven (other libraries like gcloud-node don't do that), but at the very least all git tagged versions should be automatically pushed to Maven...

/cc @jboynes

**Comment by aozarov** [comment]
@jgeewax , I don't think this belongs in this milestone.
Maven pushes could be done manually until this issue is resolved.
I think for the this milestone we just want to make sure we have a push that corresponds to all changes associated with this milestone.

**Comment by jgeewax** [comment]
What I'm worried about is too much reliance on manual pushes -- if we need to get something out quickly, it would be great to have "all our ducks in a row" with regard to process so a tag gets pushed to maven.

If having Travis handle publishing was an enormous undertaking (which I suspect it's not, but let's say it is) then I could see us pushing this back. Otherwise, I would really prefer to have this (and the other process-focused things) ready before announcing publicly.

**Comment by aozarov** [comment]
Travis is now configured to push a SNAPSHOT to maven every successful build.

Non snapshot builds are still done manually and should include the following:
- Update pom files to reflect the build number
- manual `maven site deploy`
- Update README.md with latest build number

**Comment by jgeewax** [comment]
Cool - thanks @aozarov 

I'm going to close this out for now, and open a separate issue focused on the non-snapshot builds, including a site update.

@stephenplusplus : Let me know if you notice anything off about what we're doing here?
