### ISSUE TITLE
Include package info example for BigQuery

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#511]
BigQuery is missing a package info example.

The PR that adds this could also fix the weird spacing on the package info examples in general (i.e. at the bottom of the [storage javadoc](http://googlecloudplatform.github.io/gcloud-java/0.1.1/apidocs/com/google/gcloud/storage/package-summary.html)).

**Comment by mziccard** [comment]
By "weird spacing" you mean the fact that the first line in the snippet seems to be less indented than the other ones? I already struggled a bit to fix that but couldn't come up with a solution that used just one `@code`.

**Comment by ajkannan** [comment]
I think if we add a space after the `<pre>` in the package info lines that say `<pre>{@code`, we can get the one-character indent that matches the other lines.

**Comment by mziccard** [comment]
It seems to me that the space after `<pre>` still does not make the indentation match but it's much better!
