### ISSUE TITLE
Create snippets for Cloud Datastore page

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/gcloud-java#541]
The Datastore docs page has a whole new set of snippets for the "getting started" guide and for the concepts snippets.

Can we implement all the necessary snippets (~50) in the [docs github](https://github.com/GoogleCloudPlatform/java-docs-samples)?

Whoever plans on owning this can ping me via email and I can give you all the necessary instructions / access to the staging docs.

**Comment by ajkannan** [comment]
If I'm understanding correctly, it seems like the Datastore Getting Started guide snippets won't use the gcloud-java API, but rather the Datastore API.  For that reason should this be an issue in the docs github you linked instead of this repo?  

Perhaps related, perhaps unrelated: gcloud-java has a couple [snippets](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/README.md#getting-started) in its readme.

**Comment by pcostell** [comment]
I think it may make sense to have both libraries listed on Datastore's docs page.

**Comment by ajkannan** [comment]
A few follow up questions:

1) Are these snippets already written, and you just need them compiled into a program(s) that can easily be downloaded and run by users?  Are the generated api client snippets the main priority, or is it an equal priority to also get some executable code that uses gcloud-java-datastore?

2) If we're also writing these snippets using gcloud-java, we probably want to make sure the java-docs-samples repo is the right place for the gcloud-java snippets.  Currently, that repo seems to mostly use generated api client libraries.

**Comment by pcostell** [comment]
1). The snippets are already written for some of the libraries. Importantly, they each have specific requirements so that the docs can talk about them in a library-agnostic way.

2). I believe this is the right place. We've put gcloud-node snippets in the node-docs-samples repo.

**Comment by ajkannan** [comment]
@lesv Should these snippets go in java-docs-samples under a new folders?  There'll be one set of snippets that uses the api client directly (proposed location: java-docs-samples/datastore/api-client) and one set of snippets that uses gcloud-java (proposed location: java-docs-samples/datastore/gcloud-java).  

Should that be the directory hierarcy for samples for other services as well?  For example, I see that Bigquery and Storage have folders in java-docs-samples already.  If/when gcloud-java code snippets are added, should they go under bigquery/gcloud-java and storage/gcloud-java?

**Comment by lesv** [comment]
We have Java Veneer samples in getting-started-java, gcloud-java/examples, and java-docs-samples.

Typically snippets go in java-docs-samples -- creating a Datastore folder at the top level is probably the best way to go.

**Comment by ajkannan** [comment]
Closing this issue since [this PR in java-docs-samples](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/90) has been merged.
