### ISSUE TITLE
Did we misname Blob as it is really holding the Blob's metadata (name, etc)?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-java#57]
Right now, Blob's are not actually the objects themselves but pointers and metadata about the blob... That being the case, should we re-evaluate the naming of the Blob class?

Some of the options:

- **`Blob`** (This is what it is today)
- Object
- StorageObject
- ObjectMetadata
- BlobMetadata
- StorageObjectMetadata
- BlobInfo

**Comment by aozarov** [comment]
Blob and Bucket were renamed to BlobInfo and BucketInfo.
A functional Blob and Bucket are planned to be added (#55) but in that case such name would be an appropriate match.
