### ISSUE TITLE
Move integration tests to different packages

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#580]
While keeping unit tests in the same package as code is useful (so that we can test package scope code), this is less important for integration tests.  Moving integration tests to a separate package would provide some benefits, such as allowing us to catch issues related to member variable access.

**Comment by jgeewax** [comment]
The example brings up a fair point -- tough to argue with that. Is this at all standard is other libraries like ours ?

**Comment by mziccard** [comment]
I have seen other projects (hibernate?) putting integration tests in a different module and package with respect to the code they test, so this is a good suggestion IMO.
