### ISSUE TITLE
Change TTL to accept unit

### ISSUE THREAD

**Issue by mderka** [GoogleCloudPlatform/gcloud-java#581]
As per suggestion of @jgeewax, change ttl in DnsRecord to accept duration as a number and TimeUnit. For an example, see e.g. here:

https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-storage/src/main/java/com/google/gcloud/storage/Storage.java#L1475

**Comment by jgeewax** [comment]
Cool - thanks for looking at this.

I was thinking this might make more sense as taking a number (ie, `123` meaning "123 seconds") as well as a Duration (ie, `Duration.ofSeconds(123)` being "123 seconds").

Does that make sense? @aozarov , @mziccard, thoughts ?

**Comment by mziccard** [comment]
If I am not mistaken [Duration.ofSeconds](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#ofSeconds-long-) is part of Java 8 and now we are sticking to java 7. 

As soon as we move to java 8 we should support `Duration` and all of java8's time support.

**Comment by mderka** [comment]
So, for now we have the <code>TimeUnit</code> solution. <code>Duration.ofSeconds</code> should be implemented when moving to Java 8.

**Comment by aozarov** [comment]
Right, I think #592 is the best we can do for now.

We already have an open issue for changing our API on Java 8 (#108) and we can use that issue as
a laundry list of things that we should change (including this one). In that case, I think we can close
this issue.. @jgeewax ?

**Comment by jgeewax** [comment]
If it's covered by #108, then sure.
