### ISSUE TITLE
Test snippet code

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#607]
It would be nice to link the snippets in the READMEs to code that we can test in Travis. That way we'd know our snippets are up to date after changes. As @mziccard points out, it's not easy to do because the snippets that we have now are simple end-to-end usage showcases (e.g. update a blob if it exists or create it if not). On the other hand our examples are more complex and command-line oriented to show the usage of each single functionality. Snippets could be part of IT tests but they will need changes anyway: asserts, data definitions, etc.

@mziccard suggests that we could create a snippet package in `gcloud-java-examples` where we put each snippet as a class+main with a meaningful name (e.g. `CreateOrUpdateBlob`). We can then reference those files before the snippet.

**Comment by aozarov** [comment]
Fixed by #635
