### ISSUE TITLE
Should we overload methods for manipulating managed zone for both id and name?

### ISSUE THREAD

**Issue by mderka** [GoogleCloudPlatform/gcloud-java#610]
The service API allows for identifying managed zones by both unsigned long id and String name. Our original intention was to overload methods for manipulating managed zones to accept both BigInteger id or String name. We are currently leaning towards not doing this, treating id as read-only value and identifying zones by name only for the purposes of manipulation (get, delete, apply change, list changes). 

Also, there is a suggestion for providing ID as String instead of BigInteger which seems to be consistent with gcloud-python and other services.

Opening this base on discussion in PR #606.

**Comment by aozarov** [comment]
+1 for not overloading. My reasons are mentioned [here](https://github.com/GoogleCloudPlatform/gcloud-java/pull/606#discussion_r51618080).

Also, +1 for changing the ID from `BigInteger` to `String` (which is more consistent with other services
that has both internal/read-only id and external id, such as project in resource-manager and bucket in storage).

**Comment by aozarov** [comment]
Also, as part of this change (making dns id read-only) we should mandate that when ZoneInfo is constructed name would never be null. I think this makes sense and would work well with the Zone changes.

**Comment by mderka** [comment]
While doing this, add options for zone create method.
