### ISSUE TITLE
Should we move Tuple<X, Y> from Rpc interfaces to common level?

### ISSUE THREAD

**Issue by mderka** [GoogleCloudPlatform/gcloud-java#615]
Whenever we need to retrieve data in pages, the Rpc interface contains a nested class `Tupe<X,Y>` which is afaik used to associate a page token with page iterable data. It is repeated code which I found in `BigQueryRpc`, `ProjectManagerRpc`, and I am now creating another copy in `DnsRpc`. We should consider moving it to the core.

**Comment by mderka** [comment]
Perhaps could be done together with #613.

**Comment by ajkannan** [comment]
It was mentioned in the discussion of #315, but we decided against adding it because we didn't want to expose a Tuple class.

**Comment by mziccard** [comment]
I am still for not exposing it.

**Comment by mderka** [comment]
Ok, got it. Then we can close this.
