### ISSUE TITLE
Adding checkstyle and other code analysis tools to our PR.

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#626]
I think that it would be nice if we have more metrics on PR (including threshold that would flag the PR as red if exceeded). Checkstyle is one of these metrics.

I was looking at the checkstyle github [page](https://github.com/checkstyle/checkstyle), just to see
if they checkstyle their own code for PR and I think they do, but I didn't invest more time on it.

I also saw that they integrate with some other github friendly sites (and free to open source projects) such as:

https://www.versioneye.com/ - for dependency out-of-date notifications
https://www.codacy.com/ - for code analysis

**Comment by mziccard** [comment]
I run codacy on our `gcloud-java`, you should be able to see the report [here](https://www.codacy.com/app/mziccard/gcloud-java/dashboard) so we can decide whether we find it useful.

**Comment by ajkannan** [comment]
My first impression is that the UI is nice and some of the suggestions are helpful, but I do think there's a lot of irrelevant errors to sift through in order to get the useful tidbits.

**Comment by aozarov** [comment]
I really like the UI and I think it would be great if we can get the PR summary (https://www.codacy.com/app/mziccard/gcloud-java/pullRequests) as part of the set of PR sets.
I have the feeling that some rules can be disabled (there is a notion of active/non-active) and customize (though I hope the latter does not mean a modified docker).
Also, some of the errors (such as "Enforce the use of explicit scoping"), can be resolved by 
code annotation (@VisibleForTesting in this [case](http://sourceforge.net/p/pmd/bugs/1410/)).

**Comment by mziccard** [comment]
> I really like the UI and I think it would be great if we can get the PR summary (https://www.codacy.com/app/mziccard/gcloud-java/pullRequests) as part of the set of PR tests.

I should have just enabled this feature for PRs against the master branch. Should we enable the tool to run on all branches? (I think we should).

Also, out of curiosity, are you able to modify codacy settings?

**Comment by aozarov** [comment]
> I should have just enabled this feature for PRs against the master branch. Should we enable the tool to run on all branches? (I think we should).

I also think we should.

> Also, out of curiosity, are you able to modify codacy settings?
Didn't try. but looks like it is doable - https://docs.codacy.com/v1.5/docs/code-patterns#2-configure-your-project-patterns no?

**Comment by ajkannan** [comment]
Closing since both versioneye and codacy PRs are merged.

**Comment by ajkannan** [comment]
Reopening since checkstyle isn't yet supported by codacy.

**Comment by mziccard** [comment]
I am closing this as Codacy now [supports Checkstyle](https://www.codacy.com/changes/54)
