### ISSUE TITLE
Support ReadOptions in v1beta3

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#637]
Read options for lookups and queries should be disabled within transactions.  Transaction options should only be available when creating a new transaction.

**Comment by ajkannan** [comment]
Disabling read options from within a transaction is a bit challenging because the `DatastoreImpl` class and the `Transaction` class both implement the `Datastore` interface.  Two ways to solve this to include:

1) Setting read options when creating a `Datastore` service object.  (If users want some actions to use eventual consistency and others to use the default level of consistency, then they could create two service objects).
2) Including varargs read options for lookup/query methods in the `Datastore` interface, but throwing an exception at runtime if a user attempts to set read options from within a transaction.

Any opinions/suggestions @aozarov @pcostell?

**Comment by aozarov** [comment]
We should also consider this option:

* Add read-only to `TransactionOption`

* Add a new `ReadOptions` class that only includes ReadConsistency settings.

* Add only to the `Datastore` interface  `get` and `run(Query)` methods that accept `ReadOptions`

* Modify Datastore implementation for runInTransaction to defer transaction creating until the first lookup or query and if none use `CommitRequest` with `TransactionOptions`

**Comment by pcostell** [comment]
I agree with Arie's proposal --

transaction options can be made available to the user at the call to `runInTransaction` or `newTransaction`. There isn't a need to expose `TransactionOptions` directly on `get` and `runQuery` calls because it's effectively an optimization that `runInTransaction` should take advantage of to avoid the call  to `beginTransaction`.

**Comment by ajkannan** [comment]
Since transaction options are coming in a later release of v1beta3, I will create a separate issue for transaction options and keep this issue for read options.

**Comment by ajkannan** [comment]
Closed via #691
