### ISSUE TITLE
List operations do not return nextPageToken which prevents proper paging

### ISSUE THREAD

**Issue by mderka** [GoogleCloudPlatform/gcloud-java#665]
When implementing integration tests for DNS, I noticed that if one restricts the fields to be retrieved for a list operation, `iterateAll()` does not work properly. The following test would always fail:

```java
dnsRecordIterator = DNS.listDnsRecords(zone.name(),
    Dns.DnsRecordListOption.fields(Dns.DnsRecordField.TYPE),
    Dns.DnsRecordListOption.pageSize(1)).iterateAll(); // to force the iterator fetch next page
  int counter = 0;
  while (dnsRecordIterator.hasNext()) {
    counter++;
  }
assertEquals(2, counter);
```

This is because the field selector silently prevents the service from returning the `nextPageToken`:

`builder.append("rrsets(").append(DnsRecordField.selector(fields)).append(')');`

instead of

`builder.append("nextPageToken,rrsets(").append(DnsRecordField.selector(fields)).append(')');`

I recall seeing the same handling in resource manage. Having discussed this with @ajkannan, this is likely a bug. The same bug may be present in other parts of the library when a combination of listing and field restriction is possible.

**Comment by ajkannan** [comment]
@mderka do you want to assign yourself this issue and fix it in BigQuery, Storage, and ResourceManager?

**Comment by aozarov** [comment]
Nice catch!!

**Comment by mderka** [comment]
I will fix it tomorrow.
