### ISSUE TITLE
What parameters should Zone/ZoneInfo builder require

### ISSUE THREAD

**Issue by mderka** [GoogleCloudPlatform/gcloud-java#698]
There are 3 things mandatory for Zone: name, dnsName and description. In my opinion, it either makes sense to allow for creating zone with name being mandatory and the rest to be part of the builder, or require all three in `ZoneInfo.builder(String name, String dnsName, String description)`. I am inclined to the first option. Should we ask for name only, or for all three?

/cc @ajkannan @aozarov @mziccard

**Comment by aozarov** [comment]
I suggest we start with only providing `ZoneInfo.builder(String name, String dnsName, String description)` if there are no more user setteble values than we could actually have instead `ZoneInfo.of(name, dnsName, String)` which returns full constructed `ZoneInfo`.

**Comment by mderka** [comment]
Ok. I like the `of()` construct.
