### ISSUE TITLE
ReadMe file as a snippet of code that is incomplete

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/gcloud-java#7]
It would be great to get a working snippet in the readme page(without looking at the javadoc first):
1/ a static method after the imports?
2/ some real content for the "..." section (or some comments in the snippet to describe what would be the value for "..."

**Comment by aozarov** [comment]
How about replacing the "..." for dataset with "'dataset-id' and "myKind" in the kind part?

I don't think that putting the code after the imports in a static method is the right thing to do (even though
that can make it a more "compilable code") for the following:
1) It is not likely that the method would be used as is.
2) adding unnecessary lines of code, just a distraction which would require another level of indentation.
3) Can't be used as is. Still need to be put in a class appropriately and I think it would be clear to an Java developer that it should also be put in some method when as-is.

In any case, I don't feel strongly about it. Let me know what you think...

**Comment by aozarov** [comment]
@ludoch So, I think we do that now for [datastore](https://github.com/GoogleCloudPlatform/gcloud-java/tree/master/gcloud-java-datastore), is that what you were thinking of?

We need one for storage as well.  Maybe something similar to the [package-info](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-storage/src/main/java/com/google/gcloud/storage/package-info.java).

Also, once  @mziccard thinks we are ready we should probably update the main readme.

**Comment by mziccard** [comment]
@aozarov I was wondering whether we should use the `Storage` interface or the functional `Blob` and `Bucket` ones in the examples (in the readme, package-info and `StorageExample`). 
I think using `Blob` and `Bucket` makes more sense for a simple usage example.

**Comment by aozarov** [comment]
> I think using Blob and Bucket makes more sense for a simple usage example.

Agree.

**Comment by aozarov** [comment]
Same snippet is now available in each module package-info as well as its README.md
