### ISSUE TITLE
any plan to export individual APIs as separate artifacts?

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-java#70]
I've noticed the the datastore and storage packages aren't setup to generate their own artifacts. Are there any plans to do this?  Java developers would typically expect each service API to be broken out and included as their own artifact.

**Comment by aozarov** [comment]
There is some discussion about it also in issue #39. The current plan is to keep having the aggregate jar that includes all services and then later on (based on demand or when we will have more services and such separation would be meaningful) we will add an artifact per service (likely via pom modules).

**Comment by patflynn** [comment]
My preference would be for it to happen as soon as you have more than one API.  It looks like you'll need separate documentation pages for datastore vs gcs pretty soon, you probably wouldn't want to include the markdown in the java package path so you'll need to break them out by parent directories. At that point you basically have the directory structure you need for the multi-module setup.

**Comment by ludoch** [comment]
Current Veneer trend is to bundle and document every thing in the same doc:
https://googlecloudplatform.github.io/gcloud-python/latest/
https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.14.0

**Comment by jgeewax** [comment]
This also follows the AWS Java trend, where everything is in a single jar.

**Comment by patflynn** [comment]
AWS seems to offer both. Each API individually, and an uber-jar for the
whole thing. That would be my preference.

**Comment by jgeewax** [comment]
Ah that's a good point. I'm fine with singular pieces as well as the jar with everything... is that a complicated thing for us to do ?

**Comment by aozarov** [comment]
Not trivial as this will including structural changes, code changes and deployment related changes ( (travis, maven, site, ..). As suggested above, I did plan to. My plan was to deal with it when we have more services and it will become more meaningful though I thought to give it a try after finishing storage. I will give a try sooner.

**Comment by aozarov** [comment]
Fixed by #74
