### ISSUE TITLE
BaseServiceException should not extend RuntimeException

### ISSUE THREAD

**Issue by dimo414** [GoogleCloudPlatform/gcloud-java#703]
Maybe this ship has already sailed, but if it's still possible `BaseServiceException` should not extend `RuntimeException`. As is, I can't confidently make *any* calls to a gcloud-java method without wrapping them in a try-catch block, and should I accidentally miss one it could cause my whole application to crash. I would suggest it extend `IOException` instead, but just extending `Exception` would be great.

**Comment by mziccard** [comment]
> I can't confidently make any calls to a gcloud-java method without wrapping them in a try-catch block

How would this be different if we extended `IOException`? You would still have to catch exceptions...

**Comment by mziccard** [comment]
If this is about checked vs unchecked exceptions my (strong) preference is to stick to unchecked. As a reference also AWS uses unchecked exceptions: [AmazonClientException](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/AmazonClientException.java#L39) extends `RuntimeException` and `AmazonServiceException` extends `AmazonClientException`.

**Comment by ajkannan** [comment]
My preference is also to stay with unchecked exceptions.  I do think we should make a pass through the library make sure every method call that can throw an exception has the exception documented with an "@throws" in the javadoc.

**Comment by aozarov** [comment]
+1 for unchecked exceptions.
This was discussed early on by various people which all favored or agreed to it.
This is also the path that gRPC (grpc-java) is taking.

**Comment by dimo414** [comment]
Well if that's the consensus fair enough; personally it's a much more error-prone experience.
