### ISSUE TITLE
Auth issue when using revoked Cloud SDK creds with local test helpers.

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#710]
When running code that uses local service emulators, users that have Google Cloud SDK installed but have out-of-date or revoked credentials (and don't specify other credentials in any other way) will see error messages when making API calls that send requests to the local emulator.  This is because we detect the Google Cloud SDK json credentials file exists, and use those to set credentials in `ServiceOptions`.  As a result, requests attempt to use these credentials (even though they aren't necessary) and fail.  

Should we:
1) Document that you should use `gcloud auth login` when using local test helpers?
or 
2) Figure out how to parse the credentials to figure out that they're valid or revoked?
I notice that under ".config/gcloud/legacy_credentials", the folder corresponding to my gcloud email account is removed when I revoke credentials.  However, I'm unsure that that's a valid way to check for revoked credentials.  The other files related to credentials in that directory don't seem to indicate whether they are valid or revoked.

**Comment by ajkannan** [comment]
A third option would be to create another subclass of `AuthCredentials` that represents "no auth".  When users set this option, they explicitly say they don't want to use auth.  By contrast, leaving the auth unset (null) in the ServiceOptions builder will use application default credentials.  In the `options` methods for the local service helpers, we can specify "no auth" so users won't see auth errors in this scenario.  If users really want to use auth with local service helpers, they can use `toBuilder()` and set auth as needed.

**Comment by aozarov** [comment]
+1 for the (3) option (Adding AuthCredentials.noAuth and using it in the Test helpers' returned options).
