### ISSUE TITLE
storage: "Failed to parse Content-Range header" when chunk-size upload is used

### ISSUE THREAD

**Issue by sudison** [GoogleCloudPlatform/gcloud-java#720]
Here is the log:

Caused by: com.google.gcloud.storage.StorageException: 400 Bad Request
Failed to parse Content-Range header.
	at com.google.gcloud.spi.DefaultStorageRpc.translate(DefaultStorageRpc.java:94)
	at com.google.gcloud.spi.DefaultStorageRpc.write(DefaultStorageRpc.java:499)
	at com.google.gcloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.gcloud.RetryHelper.doRetry(RetryHelper.java:181)
	at com.google.gcloud.RetryHelper.runWithRetries(RetryHelper.java:247)
	at com.google.gcloud.RetryHelper.runWithRetries(RetryHelper.java:237)
	at com.google.gcloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:46)
	at com.google.gcloud.BaseWriteChannel.close(BaseWriteChannel.java:147)

If I uploaded a file with size is exactly 2 x 1024 x 1024, and 1024 x 1024 as the chunk size, then I'll get above exception. However, if I changed the file size to 2 x 1024 x 1024 + 1, then the problem will go away.

Apparently, there is a bug in BlobWriteChannel->flushbuffer, if there is no data available, then there is no need to call options().rpc().write.

**Comment by mziccard** [comment]
Hi @sudison thanks for the report. I managed to reproduce you issue, I will look into this and provide a fix as soon as possible.

**Comment by jean-philippe-martin** [comment]
PR #714 has a potential fix for that, making a note to try the repro after that request is merged.

**Comment by sudison** [comment]
I tried the fix in https://github.com/jean-philippe-martin/gcloud-java/commit/73b9ef67e4eb01530a315dea74559cb203f7535a, I got

com.google.api.client.http.HttpResponseException: 400 Bad Request
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "badRequest",
    "message": "Invalid Upload Request"
   }
  ],
  "code": 400,
  "message": "Invalid Upload Request"
 }
}

if length is zero, sending a upload request to cloud storage, will get above exception.

**Comment by aozarov** [comment]
Yes, @sudison thank you. We realized that but unfortunately only added a [comment](https://github.com/GoogleCloudPlatform/gcloud-java/pull/714#discussion_r55251012) in the PR and not here. We are waiting to see if there is a good way to fix that other than applying a workaround to fix it.

**Comment by sudison** [comment]
My fix for this issue is to add a method: 
  void totalLength(long length);
on WriteChannel. 
The assumption is that, caller knows the length of the file before uploading to GCS.

**Comment by aozarov** [comment]
Indeed that is a way, but I don't think we should make knowing the total lengths a requirement (and GCS should be able to support it). There are various cases where one would not know the length and we would like to support them to.

**Comment by jean-philippe-martin** [comment]
Agreed. Having to specify the length would make Java NIO integration really hard as NIO users don't give the length before starting their writes via e.g. [newOutputStream](https://docs.oracle.com/javase/7/docs/api/java/nio/file/spi/FileSystemProvider.html#newOutputStream(java.nio.file.Path,%20java.nio.file.OpenOption...)).

**Comment by sudison** [comment]
As a user, if I want to use this library now, what should I do? This is the basic requirement for a library which can upload/download a file.

**Comment by aozarov** [comment]
We will fix it soon. How big is your `Blob`? Can you apply one of the `create` methods that takes the blob content in the meantime?

**Comment by sudison** [comment]
Ok, thanks. Blob is around 1 - 20 MB. Is create method ok for such blob?

**Comment by aozarov** [comment]
20MB is on the bigger side but Yes, and you can use the `create` that accepts `InputStream` if you don't have the content in memory.

**Comment by sudison** [comment]
ok, thanks. then I'll use create for now.
