### ISSUE TITLE
storage: read blob in chunk will get exception when reach the end the blob

### ISSUE THREAD

**Issue by sudison** [GoogleCloudPlatform/gcloud-java#723]
Following code is used to read blob chunk by chunk:

```java
try (ReadChannel reader = blob.reader()) {
  WritableByteChannel channel = Channels.newChannel(outputStream);
  ByteBuffer bytes = ByteBuffer.allocate(64 * 1024);
  while (reader.read(bytes) > 0) {
    bytes.flip();
    channel.write(bytes);
    bytes.clear();
  }
}
```

reader.read() will throw exception:

com.google.gcloud.storage.StorageException: java.lang.NullPointerException

	at com.google.gcloud.storage.StorageException.translateAndThrow(StorageException.java:74)
	at com.google.gcloud.storage.BlobReadChannel.read(BlobReadChannel.java:159)

The root cause is, reader is blindly reading chunks from cloud storage, if it reaches beyond the end of the blob, then cloud storage will throw an error: 416 Requested range not satisfiable.

**Comment by mziccard** [comment]
Hey @sudison thanks for the report. Unfortunately I did not manage to reproduce the error. Which version of gcloud-java are you using? How big is the blob you are trying to read? 

Thanks

**Comment by sudison** [comment]
blob size is 2 x 1024 x 1024, gcloud version is 0.1.4

**Comment by aozarov** [comment]
FYI, I sent #725 to fix the write issue.

**Comment by aozarov** [comment]
@sudison Thanks, I can reproduce that and will fix that together with #220

**Comment by aozarov** [comment]
#725 should fix both issues (waiting for a reviewer before it can get merged).

**Comment by mziccard** [comment]
@sudison We just merged #725 so this should be fixed in master now. We will release a new version of `gcloud-java` soon to make this fix available through in maven. I'll write here as soon as we release the new artifact.

**Comment by sudison** [comment]
Thanks for the quick fixes. Tested locally, it works.

**Comment by mziccard** [comment]
@sudison Thanks to you for reporting the issues! Version 0.1.5 is out now and includes the fixes!
