### ISSUE TITLE
Small Blobs silently stored as ShortBlobs - Need option to force full Blob

### ISSUE THREAD

**Issue by unitydynamics** [GoogleCloudPlatform/gcloud-java#724]
Maybe there is an option but someone will have to point it out to me: how can I ensure that my Blobs are stored as full Blob objects and not ShortBlobs?  

The issue for me is that I'm writing entities to the datastore using gcloud-java and then reading them with Objectify.  When reading I see the error: `Expected class com.google.appengine.api.datastore.Blob, got class com.google.appengine.api.datastore.ShortBlob: <ShortBlob: 247 bytes>`

I'm inserting my Blobs like this:
`entityBuilder.set("compressedText", BlobValue.builder(Blob.copyFrom(compressedtext)).build());`
where compressedtext is a byte[]

**Comment by unitydynamics** [comment]
Also just FYI I've posed this as a potential Objectify change: https://github.com/objectify/objectify/issues/284

**Comment by aozarov** [comment]
From the Google Cloud Datastore perspective there is only one [type](https://cloud.google.com/datastore/docs/concepts/entities#properties_and_value_types) of Blob which is a `Byte String`.

I think Objectify need to map/handle `ShortBlob` in a similar way they do for `Blob`.
BTW, a similar concept should apply to `Text` and `String` (Google Cloud Datastore has only one
field for it, `stringValue`).

**Comment by unitydynamics** [comment]
Thanks I suppose I just assumed that ShortBlob was a datastore primitive ([this page](https://cloud.google.com/appengine/docs/java/datastore/entities)).  Jeff has very graciously agreed to fix this in Objectify.  I think we can close this out.
