### ISSUE TITLE
Datastore Javadoc includes example programs and more...

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/gcloud-java#733]
It's nice to have around, but a clean API for Javadoc is also very useful.

Ideally, you would have just the API JavaDoc as the Reference Doc, and then if you want another doc w/ examples.

**Comment by aozarov** [comment]
@lesv I am not sure I follow you.

Are you saying that you would like to take examples out of the javadoc (if so, can you point to some places, so we can discuses in more specifics). Also, what "and more..." is referring to?

**Comment by lesv** [comment]
I'm talking about: http://googlecloudplatform.github.io/gcloud-java/0.1.5/apidocs/?com/google/gcloud/bigquery/package-summary.html

It would be nice if it were missing the examples and testing classes, so all-classes just had classes the developers can call by including the gcloud-java artifact.

**Comment by aozarov** [comment]
Ah, I see. the packages with the ".test" suffix are not test but rather Test helpers (help the API users to test their code when using `gcloud-java`). I agree that taking out examples (and maybe even spi) from the main javadoc site would be a good thing.

**Comment by aozarov** [comment]
@lesv see last image in #738. Changes will be publicly visible in the next release.
Is there anything else that is not covered or can we close the issue?

**Comment by lesv** [comment]
LGTM
