### ISSUE TITLE
Standardize "maxResults"/"pageSize" option terminology

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#740]
We use "pageSize" in Resource Manager and "maxResults" in Storage and BigQuery to mean "max results per page".  We should standardize our terminology.  I slightly prefer the term "pageSize" because a user could want some total number of results that's greater than what the service allows as the pageSize.  As a result, the user might set a "maxResults" field, get less results than they asked for, and perhaps assume (without checking the page token) that they got all the results that existed, even if there is another page of results.

We should standardize the javadoc to include that it's "the maximum number of results returned per page."

**Comment by mderka** [comment]
+1 for unifying on `pageSize`. It seems more intuitive.
