### ISSUE TITLE
Improve PR coverage tooling

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#752]
The Coveralls plugin version 4.1.0 is very slow, much slower than version 3.1.0.  As a result, we don't get coverage results in a timely fashion when reviewing PRs.  Downgrading the Maven Coveralls version to 3.1.0 seems to make the coverage reports appear faster.  Alternatively, we can see whether using a different coverage analysis tool might be faster than using Cobertura.  One possibility is to use Jacoco rather than Cobertura (perhaps the input is parsed faster by Coveralls).  Jacoco seems to [work with Coveralls](https://github.com/trautonen/coveralls-maven-plugin/issues/93) and also seems to have a [couple additional features](https://confluence.atlassian.com/display/CLOVER/Comparison+of+code+coverage+tools) that Cobertura doesn't.

**Comment by mziccard** [comment]
I think we are not seeing this latency anymore. See for instance [this build](https://travis-ci.org/GoogleCloudPlatform/gcloud-java/builds/146605222), the job that generates the coverall report is not much slower that other jobs. And as soon as that job is done the report is almost immediately added to the PR. @ajkannan do you remember which kind of latency we were experiencing?

**Comment by ajkannan** [comment]
Yeah, it looks like this isn't a problem anymore.  The issue back when I wrote this was that Travis hung while trying to send report information to Cobertura (when using version 4.1.0).  After it spun for a while, it would give up and fail.  Now it doesn't doesn't seem to do that, since I see the report in Coveralls and the time looks fine, and we're using 4.1.0.
