### ISSUE TITLE
Both pageToken and startPageToken are used as list options

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#759]
As noticed by @mderka we are using `pageToken` in `resourcemanager` while `startPageToken` in `storage` and `bigquery`. We should probably pick a name and stick to it.

My feeling is that `pageToken` is already clear enough so we can go with it and remove all `startPageToken`. What do you guys think?

**Comment by ajkannan** [comment]
Nice catch @mderka.  I second the vote for `pageToken`.
