### ISSUE TITLE
Update example documentation with correct APIs to enable (if necessary)

### ISSUE THREAD

**Issue by jean-philippe-martin** [GoogleCloudPlatform/gcloud-java#790]
Check whether we need to tell people to enable both"Google Cloud Storage" and "Google Cloud Storage JSON API". If so, update the docs.

Context: [#714 (comment)](https://github.com/GoogleCloudPlatform/gcloud-java/pull/714#discussion_r57408959).

**Comment by ajkannan** [comment]
Fixed by #852 and #864.
