### ISSUE TITLE
Improve the method names in BackoffParams

### ISSUE THREAD

**Issue by shinfan** [GoogleCloudPlatform/gcloud-java#814]
Right now method names only fit for retry settings but not the timeout.

**Comment by garrettjonesgoogle** [comment]
I think we should just flatten the backoff params into retry params. Our client-side config will have them flattened, e.g.

          "initial_retry_delay_millis": 100,
          "retry_delay_multiplier": 1.2,
          "max_retry_delay_millis": 1000,
          "initial_rpc_timeout_millis": 2000,
          "rpc_timeout_multiplier": 1.5,
          "max_rpc_timeout_millis": 30000,
          "total_timeout_millis": 45000

**Comment by mziccard** [comment]
Closing this as was fixed in https://github.com/googleapis/gax-java/pull/44
