### ISSUE TITLE
Create a retry helper that doesn't retry on socket timeouts

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#816]
For non-reentrant operations (e.g. creating resources and applying a change request), we should have a separate retry handler that won't retry on socket timeouts.  This is because a socket timeout error can occur after a request was successfully sent to the service.  This would be helpful in DNS (see issue #808), but may also be helpful in other services.

**Comment by aozarov** [comment]
This was fixed by #883.
