### ISSUE TITLE
Better naming for resource identities and service ids

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#824]
Our `XxxInfo` classes have two fields with a similar name
- `xxxId`: this fields is of type `XxxId` and holds a user-defined identity for the resource
- `id`: this fields holds a service-generated (opaque) id

We should provide a better naming to easily distinguish the two fields. Possible solutions are:
- renaming `id` to `generatedId` (this is the preferred way so far)
- renaming `id` to `opaqueId`

Note: this issue also applies to other classes (e.g. compute's `DiskImageConfiguration`).

**Comment by ajkannan** [comment]
I'm +1 for `generatedId`

**Comment by mziccard** [comment]
Just added the compute label, this must remain open unti fixed in compute.

**Comment by aozarov** [comment]
I guess this can be closed now?

**Comment by mziccard** [comment]
Fixed with #832 and #966
