### ISSUE TITLE
Credentials fail with "Cloud Datastore API not enabled"

### ISSUE THREAD

**Issue by volgin** [GoogleCloudPlatform/gcloud-java#843]
I use the same credentials to access Cloud Storage API and Cloud Datastore API. Both APIs are enabled for my project. The Cloud Storage works as expected. Datastore fails with:

```
com.google.datastore.v1beta3.client.DatastoreException: The Cloud Datastore API is not enabled for the project rebelplayercom, code=FAILED_PRECONDITION
	at com.google.datastore.v1beta3.client.RemoteRpc.makeException(RemoteRpc.java:126)
	at com.google.datastore.v1beta3.client.RemoteRpc.makeException(RemoteRpc.java:169)
	at com.google.datastore.v1beta3.client.RemoteRpc.call(RemoteRpc.java:89)
	at com.google.datastore.v1beta3.client.Datastore.lookup(Datastore.java:92)
	at com.google.gcloud.datastore.spi.DefaultDatastoreRpc.lookup(DefaultDatastoreRpc.java:137)
```

At least one more user reported the same problem yesterday on StackOverflow. He also claims that the Datastore API is enabled for his project.

Note that the API explorer shows v1beta2 for Cloud Datastore API, not v1beta3. Can it be the cause of this problem?

**Comment by ajkannan** [comment]
Hi @volgin, thanks for creating this issue.  The latest version of our Datastore client library (version 0.1.7) uses Cloud Datastore v1beta3, which is not enabled by default for some users.  Try enabling the v1beta3 API on the Developer's Console using [this link](https://console.cloud.google.com/apis/api/datastore.googleapis.com).

Even if you had the Datastore API enabled previously, it may be the v1beta2 version, which has recently been renamed to "Google Cloud Datastore API (v1beta2)" the Developer's Console.

Let me know if that solution works for you.

**Comment by volgin** [comment]
This API is not listed in popular APIs. In fact, the popular APIs show Cloud Datastore API, which links to v1beta2. I was able to find the "new" Datastore API only using the search field. I am sure you will fix this soon.

**Comment by ajkannan** [comment]
Yes, I've pinged people about when they plan to update that "popular APIs" link, and I'll keep tabs to see that it gets updated.

**Comment by aozarov** [comment]
@ajkannan can we close the issue? Did the Datastore team completed the back-fill and "Cloud Datastore API" link now points to v1beta3?

**Comment by ajkannan** [comment]
The Datastore team merged in a change to update the link, but the link will only change for users once the next release of the Developer's Console is out.  They said it should be released by today afternoon.  Shall we keep the issue open until then?

**Comment by ajkannan** [comment]
Closing this as the API link change has been released.
