### ISSUE TITLE
Language switcher uses the wrong logo for Ruby

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-java#846]
We're using the Rails logo, not the Ruby logo -- can we switch this out ASAP?

Here's the list of logos:

https://github.com/GoogleCloudPlatform/gcloud-node/tree/gh-pages/src/images

**Comment by mziccard** [comment]
Should be ok now in deployed sites (might need to clear the cache). I'll send a PR to update the logo for future sites.

BTW, our landing page might benefit a thorough check to see that we are aligned with other gcloud-* projects.

**Comment by jgeewax** [comment]
The other sites logos are good -- shouldn't need anything else.

Going forward, we should start exporting our doc data to the standard
format so we don't have to maintain our own gh-pages stuff :
https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/site

**Comment by aozarov** [comment]
> Going forward, we should start exporting our doc data to the standard
format so we don't have to maintain our own gh-pages stuff :

Providing a json-based doc **instead** of what we have now in gh-pages (which
includes among others Javadoc, and standard maven project information) would be a mistake
in my mind. Providing it in addition is probably fine (though I would expect Java people to be
more comfortable and prefer the javadoc over other doc formats).

**Comment by jgeewax** [comment]
Yes, this is not **instead** -- but in addition.
