### ISSUE TITLE
BigQueryJob returns false if it does not exists

### ISSUE THREAD

**Issue by mderka** [GoogleCloudPlatform/gcloud-java#851]
On line 183, the job return `false` if it is `null`. It makes more sense for it to return `true`. A job once created cannot be deleted. If a user somehow obtained a non-null `Job` instance, the only way for this get to receive `null` is that the job was completed and somehow perished.

/cc @aozarov @mziccard

**Comment by aozarov** [comment]
Agree to the above though I would like to mention the other option of throwing an exception if we detect that this job no longer exists.

I think both of these options are better than getting an infinite loop by waiting for a non-existing job to complete.

**Comment by mziccard** [comment]
Nice catch. FYI job information is no longer available after six months from job creation.
I think I would return `true` if you do not have any string argument against.

This issue also applies to compute's operations where operations can be deleted only if they have already completed their execution. Even for compute I would return `null` if the operation does not exist.

**Comment by mziccard** [comment]
Leaving this open for compute

**Comment by mziccard** [comment]
This was fixed in #853 and #914
