### ISSUE TITLE
Make it easier to create ListValue by adding specific type flavours of ListValue.of method

### ISSUE THREAD

**Issue by aozarov** [GoogleCloudPlatform/gcloud-java#886]
e.g. `ListValue.of(String..)`, `ListValue.of(double...)`,...

**Comment by ajkannan** [comment]
Right now we have [this](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/gcloud/datastore/BaseEntity.java#L428) for each value type.  Would ListValue.of(String...) add a lot of value?

**Comment by aozarov** [comment]
Yes, the difference is that such addition would make it easy creating a list independent of an Entity when that is desired.

**Comment by aozarov** [comment]
On the same note, we could even make ListValue creation easier by also supporting an overloaded
addValue version in the `Builder` for each of the acceptable types.
