### ISSUE TITLE
Broken links to Github repos in Maven-generated website 

### ISSUE THREAD

**Issue by ajkannan** [GoogleCloudPlatform/gcloud-java#903]
On one of our website pages ([see here](http://googlecloudplatform.github.io/gcloud-java/0.1.7/gcloud-java/dependencies.html)), the links to our modules under `ArtifactId` in the `compile` section and some of the links to transitive dependencies below are broken because they don't use `/tree/master` in the URLs.  For example, the link to gcloud-java-datastore is `https://github.com/GoogleCloudPlatform/gcloud-java/gcloud-java-datastore` instead of `https://github.com/GoogleCloudPlatform/gcloud-java/tree/master/gcloud-java-datastore`.

**Comment by ajkannan** [comment]
This is fixed in the master and gcs-nio branches, now just has to be left open for compute.  (It isn't worth it to figure out the broken links in transitive dependencies as mentioned in the OP.)

**Comment by mziccard** [comment]
Fixed in #927
