### ISSUE TITLE
DNS batch request URLs contain host

### ISSUE THREAD

**Issue by mderka** [GoogleCloudPlatform/gcloud-java#929]
The individual requests in the multipartite batch request contain the scheme and host:

`/dns/v1/projects/dummyprojectid/managedZones`

vs

`http://localhost:43754/dns/v1/projects/dummyprojectid/managedZones`

Therefore, in `LocalDNSHelper` in the `pickHandler` method, we sometime relativize the URI directly and sometimes extract path first. We should investigate if this is the correct way or if we should make the queued batch requests consistent in providing URI without the scheme (by not setting host in the `options`).

**Comment by mziccard** [comment]
A workaround to this has been added in #938. This issue should remain open until we figure out whether the way batch requests are built will change (and in that case we should remove the workaround).

**Comment by mziccard** [comment]
Closing this issue as it seems that batch requests won't change.
