### ISSUE TITLE
Support Container Engine for default credentials

### ISSUE THREAD

**Issue by firstthumb** [GoogleCloudPlatform/gcloud-java#935]
Container Engine runs on Compute Engine and I have tried to connect datastore from Container Engine
`DatastoreOptions.defaultInstance().service()`
It throws authentication exception. I think It should support with default credentials, it still runs on Google Cloud Sandbox

**Comment by mziccard** [comment]
Hi @firstthumb, thanks for the report! Could you please post here the stacktrace?
Also is the `Google Cloud Datastore API` enabled for your project (the same project where you run your containers, as you are not providing a different one if you are using `defaultInstance()`)? You should be able to check that [here](https://console.cloud.google.com/apis/api/datastore.googleapis.com/).

**Comment by mziccard** [comment]
Also, when you created the cluster did you enable it to access the Datastore service?
To do that in [https://console.cloud.google.com/kubernetes/add](https://console.cloud.google.com/kubernetes/add) click the **More** link:

<img width="300" alt="morebutton" src="https://cloud.githubusercontent.com/assets/450933/14600375/8db30106-055c-11e6-8f44-97036fbe4d6c.png">

And then enable the Datastore service:

<img width="300" alt="enabledatastore" src="https://cloud.githubusercontent.com/assets/450933/14600433/d9c50134-055c-11e6-9e20-6fbf5dff47d7.png">

**Comment by firstthumb** [comment]
Yes, you are right. It works now. I did wrong setup for the cluster before.
