### ISSUE TITLE
Add support for EmbeddedEntity in Datastore

### ISSUE THREAD

**Issue by volgin** [GoogleCloudPlatform/gcloud-java#972]
Currently there is no support for embedded entities and no mentions of them in the documentation or Datastore example.

**Comment by mziccard** [comment]
Actually this is supported.
You can set an entity as a property of another entity by using either [`set(String, Value<?>)`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/cloud/datastore/BaseEntity.java#L140) and passing an [`EntityValue`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/cloud/datastore/EntityValue.java) or by using the newly released [`set(String, FullEntity<?>)`](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-datastore/src/main/java/com/google/cloud/datastore/BaseEntity.java#L361).

**Comment by volgin** [comment]
It will be nice to add this information to the Datastore example and JavaDoc.

**Comment by mziccard** [comment]
> It will be nice to add this information to the Datastore example and JavaDoc.

Javadoc should already be in place. I will take care of adding this to the example.

**Comment by mziccard** [comment]
An example for datastore's embedded entities has been added in #980, see [here](https://github.com/GoogleCloudPlatform/gcloud-java/blob/master/gcloud-java-examples/src/main/java/com/google/cloud/examples/datastore/DatastoreExample.java#L215).
