### ISSUE TITLE
Travis Skips Tests??

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/gcloud-java#985]

**Comment by mziccard** [comment]
Could you provide some more details on this?

**Comment by waprin** [comment]
I asked JJ why -DskipTests=true was in the Travis script and he suggested I file an issue. Tests seem to have some failures on just a plain 'mvn install'.

**Comment by waprin** [comment]
Now I see that the verify scripts exist, I hadn't looked in a while and I asked JJ about it and he was like "file an issue right now!" :) Should have looked further first.
