### ISSUE TITLE
Method names in StructuredQuery.PropertyFilter are non-obvious

### ISSUE THREAD

**Issue by eamonnmcmanus** [GoogleCloudPlatform/gcloud-java#99]
StructuredQuery.PropertyFilter includes these static methods:
* `eq`
* `gt`
* `gte`
* `le`
* `lte`

I think it's very non-obvious that `le` in particular means less-than rather than less-than-or-equal. I propose spelling out these names:

* `equals(String property, T value)`
* `greaterThan`
* `greaterThanOrEqual`
* `lessThan`
* `lessThanOrEqual`

**Comment by aozarov** [comment]
I tried to minimize unnecessary verbosity and preferred being concise when possible but I agree that in this case the result is confusing.

I am fine with being more verbose as suggested above.

Another option would be the apply the following (bash style) changes:

current | suggestion
---|---
le | lt
lte | le
ge | gt
gte | ge
