### ISSUE TITLE
What should Subscription.topic return when the topic is deleted

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#991]
When a topic is deleted its subscriptions are not. For such subscriptions the `topic` field assumes the special value `"_deleted-topic_:`. What should `Subscription.topic()` getter return in this case? I see two main options (there surely are more).
- `Subscription.topic()` returns `null`
- `Subscription.topic()` returns `TopicId.of("_deleted-topic_")`

Regardless, this should be properly documented.
/cc @aozarov @eschapira to hear your thoughts

**Comment by eschapira** [comment]
I suggest to have a singleton and add the method isDeleted to topic.
Returning null is semantically correct, but nulls are problematic and can
crash the app inadvertently.

The next question is what to do when any method is called on the deleted
topic. You can throw NotFound on the singleton, or just call the server,
but the error will be less intuitive.

**Comment by mziccard** [comment]
Closed with #984
