### ISSUE TITLE
Iterator.next() is ignored for List<Value<T>>

### ISSUE THREAD

**Issue by volgin** [GoogleCloudPlatform/gcloud-java#993]
This code produces an endless loop:

```
List<Value<Long>> releases = entity.getList("releases");
System.out.println(releases.size());    // prints 1 

while (releases.iterator().hasNext()) {
	Value<Long> value = releases.iterator().next();
	System.out.println(value.get());   // prints correct value over and over
}

```

**Comment by ajkannan** [comment]
The condition in the while loop creates a new iterator for each iteration of the loop, which causes the infinite loop.  If you save the iterator you create before the while loop rather than creating a new one each time, the problem should be fixed.

**Comment by volgin** [comment]
Is this documented? Typically I don't expect a new iterator created when I simply pass a reference to it.

-----Original Message-----

**Comment by ajkannan** [comment]
`releases` is of type `java.util.List` (which is [`Iterable`](https://docs.oracle.com/javase/7/docs/api/java/lang/Iterable.html)).  The contract of `Iterable`'s `iterator()` is to return a new iterator over all items in the list.  The code you provide would also loop endlessly if you used some other generic type (e.g. Integer), like below:

```
List<Integer> releases = Collections.singletonList(1);
System.out.println(releases.size());

while (releases.iterator().hasNext()) {
    int value = releases.iterator().next();
    System.out.println(value);
}
```

**Comment by volgin** [comment]
OK. Thank you for a quick response, and feel free to close this issue.
