### ISSUE TITLE
Add to Builder methods to Datastore's classes

### ISSUE THREAD

**Issue by mziccard** [GoogleCloudPlatform/gcloud-java#994]
Datastore's `ProjectionEntity`, `IncompleteKey`, `Entity` and `Key` have static builder methods:
```java
public static Builder builder(ProjectionEntity copyFrom)
public static Builder builder(IncompleteKey copyFrom)
public static Builder builder(Entity copyFrom)
public static Builder builder(Key copyFrom)
```

In other modules we use a `toBuilder()` instance method to create builders from entity objects. Should we use `toBuilder()` also in Datastore? Or is there a reason to prefer static `builder(ResourceType copyFrom)`? \cc @ajkannan @aozarov

**Comment by ajkannan** [comment]
It would be nice to add `toBuilder`, but I encountered some issues with inheritance when I tried to add those methods.  I briefly described the problem I ran into in #628.

**Comment by mziccard** [comment]
Now I see, it seems more complex than I expected. I am closing this for now. Will reopen in case somebody else feels like those methods should be added. Thanks @ajkannan.
