### ISSUE TITLE
Blob creation fails when deploying in an Android device

### ISSUE THREAD

**Issue by rafaelsf80** [GoogleCloudPlatform/gcloud-java#995]
Hello,

Trying to deploy this [snippet code](https://github.com/GoogleCloudPlatform/gcloud-java#google-cloud-storage) into an Android device, I got the a _NoSuchMethodError_ run-time exception saying that crc32c() static method does not exist in class com.google.common.hash.Hashing.

The exception is thrown at line where the blob is created:
`                    Blob blob = storage.create(blobInfo, "Hello, Cloud Storage!".getBytes(UTF_8));
`

The whole Android code [here](https://github.com/rafaelsf80/cloud-storage-android).
Any suggestion would be appreciated.

**Comment by mziccard** [comment]
Hi @rafaelsf80,

it seems that an older version of guava is being deployed... This is strange... Try adding an explicit exclusion:
```groovy
exclude group: 'com.google.guava', module: 'guava-jdk5'
```

**Comment by rafaelsf80** [comment]
Hi @mziccard 
Thanks for your answer, I added this as suggested, but unfortunately still same error related to crc32c static method:

```javascript
compile ('com.google.cloud:gcloud-java-storage:0.2.1') {
        exclude group: 'com.google.api-client', module: 'google-api-client-appengine'
        exclude group: 'com.google.guava', module: 'guava-jdk5'
    }
compile 'com.google.apis:google-api-services-storage:v1beta1-rev131-1.22.0'
```

**Comment by mziccard** [comment]
Try this:
```
compile ('com.google.cloud:gcloud-java-storage:0.2.1') {
        exclude group: 'com.google.api-client', module: 'google-api-client-appengine'
        exclude group: 'com.google.guava', module: 'guava-jdk5'
}
compile ('com.google.apis:google-api-services-storage:v1beta1-rev131-1.22.0') {
        exclude group: 'com.google.guava', module: 'guava-jdk5'
}
```

**Comment by rafaelsf80** [comment]
Thanks again for your quick answer. Unfortunately, the problem remains with the same exception at run-time, related to the crc32c method. Thanks.

**Comment by mziccard** [comment]
Could you double check? Maybe cleaning the build first? I've just tried and I managed to create the blob.

**Comment by rafaelsf80** [comment]
sorry, thanks, my mistake. It worked :)
Thanks for your quick help

**Comment by mziccard** [comment]
You're welcome :)
